Gemfile
Gemfile.lock
app/concepts/incident/operation/create.rb
app/concepts/incident/operation/save.rb
app/concepts/incident/operation/update.rb
app/concepts/jwt_api_entreprise/operation/admin_create.rb
app/concepts/jwt_api_entreprise/operation/user_create.rb
app/concepts/role/operation/create.rb
app/concepts/role/operation/db_seed.rb
app/concepts/user/operation/add_roles.rb
app/concepts/user/operation/confirm.rb
app/concepts/user/operation/create.rb
app/concepts/user/operation/login.rb
app/controllers/jwt_api_entreprise_controller.rb
app/controllers/roles_controller.rb
app/controllers/users_controller.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/doorkeeper.rb
spec/concepts/jwt_api_entreprise/operation/admin_create_spec.rb
spec/concepts/jwt_api_entreprise/operation/user_create_spec.rb
spec/concepts/role/operation/create_spec.rb
spec/concepts/role/operation/db_seed_spec.rb
spec/concepts/user/operation/add_roles_spec.rb
spec/concepts/user/operation/confirm_spec.rb
spec/concepts/user/operation/create_spec.rb
spec/concepts/user/operation/login_spec.rb
spec/helpers/factories/users.rb

Monté de version de Trailblazer vers la *release candidate* 2.1.0.rc13 : 
* supression au passage de trailblazer-loader et donc renommage des constantes en accord avec les conventions Rails
* Injection de dépendances via *ClassDependencies* n'est plus supportée
* Déprécation annoncée de la macro *Nested* en faveur de *Subprocess*
Commits par commit

Trailblazer 2.1.rc13

---

app/serializers/user_index_serializer.rb
spec/controllers/users_controller_spec.rb

Ajout de :created_at au retour de user/index, sur une demande de @mazalaigue

user index now returns :created_at

---

.travis.yml
app/mailers/application_mailer.rb
app/mailers/jwt_api_entreprise_mailer.rb
app/models/jwt_api_entreprise.rb
app/views/jwt_api_entreprise_mailer/expiration_notice.html.erb
app/views/jwt_api_entreprise_mailer/expiration_notice.text.erb
app/views/user_mailer/confirm_account_action.html.erb
app/views/user_mailer/confirm_account_action.text.erb
app/views/user_mailer/confirm_account_notice.html.erb
app/views/user_mailer/confirm_account_notice.text.erb
app/views/user_mailer/token_creation_notice.html.erb
app/views/user_mailer/token_creation_notice.text.erb
config/application.rb
config/deploy.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/schedule.yml
spec/mailers/jwt_api_entreprise_mailer_spec.rb
spec/mailers/user_spec.rb
spec/models/jwt_api_entreprise_spec.rb

Normalement derniers changements avant déploiement en production : 
* un format plus *user friendly* de la date d'expiration dans le corps du mail ; 
* le propriétaire du compte ainsi que tous les contacts métiers et techniques reçoivent l'email ; 
* la tâche Sidekiq CRON est exécutée toutes les 4h (le *pourquoi* est explicité en commentaire du commit) ; 
* l'adresse email de "l'envoyeur" a été externalisée dans les fichiers de configuration par environnements (qui sont déployés par Ansible, et qui vaut dorénavant *support@entreprise.api.gouv.fr*) 
Commits par commits.
Je suis pas trop fan du nom de ma variable pour l'adresse email *from* ; si ça vous va, très bien, sinon proposez autre chose.
Idem pour mon code qui gère l'envoie aux différents contacts métiers et business, sans être …

Amélioration des alertes d'expiration des jetons

---

.travis.yml
app/concepts/jwt_api_entreprise/operation/admin_create.rb
app/concepts/jwt_api_entreprise/operation/user_create.rb
app/concepts/user/operation/confirm.rb
app/concepts/user/operation/create.rb
app/models/jwt_api_entreprise.rb
lib/tasks/create_admin.rake
spec/concepts/user/operation/confirm_spec.rb
spec/concepts/user/operation/create_spec.rb
spec/factories/jwt_api_entreprise.rb
spec/factories/users.rb
spec/lib/account_access_token_spec.rb

- `Time.xxx` se base sur l'heure de la machine.
- `Time.zone.xxx` se base sur le fuseau horaire définit dans `config/application.rb` (`config.time_zone = 'Europe/Paris'`)
Il faut donc utiliser partout `Time.zone.xxx` pour que les tests passent sur des machines sur un autre fuseau horaire...
Et donc on peut supprimer la configuration Travis qui forçait le fuseau horaire à Paris pour que les tests passent ; ça n'est plus nécessaire

Use Time.zone instead of Time

---

app/concepts/user/contract/confirm.rb
app/concepts/user/contract/create.rb
app/concepts/user/operation/confirm.rb
config/dry_validation_errors.yml
spec/concepts/user/operation/confirm_spec.rb
spec/concepts/user/operation/create_spec.rb
spec/controllers/users_controller_spec.rb
spec/helpers/factories/users.rb

* la date d'acceptation des CGU doit maintenant être fournie dans les paramètres de la requête de création d'un utilisateur. L'attribut n'est plus set lors de la confirmation du compte.
Initialement il y avait une case à cocher pour l'acceptation des CGU dans le formulaire de confirmation de compte utilisateur. A présent cette case à cocher est déjà présente dans le formulaire de demande d'accès Signup. C'est donc Signup qui fourni la date d'acceptation des CGU à la validation de la demande qui créé maintenant un compte usager automatiquement.
Supprimer la checkbox du formulaire de confirmation de compte (qui contiendra uniquement le mot de passe et la confirmation).

Fournir la date d'acceptation des CGUs à la création d'un utilisateur

---

app/models/user.rb
app/serializers/user_show_serializer.rb
spec/controllers/users_controller_spec.rb
spec/factories/jwt_api_entreprise.rb
spec/factories/users.rb
spec/models/user_spec.rb

Ajoute la liste des jetons archivés dans la payload de retour du détail d'un utilisateur (sur le même principe que les jetons blacklistés).

Renvoyer les jetons archivés dans le détail d'un user

---

app/concepts/contact/contract/upsert.rb
spec/concepts/contact/contract_spec.rb

In order to accept DOM TOM phone number for example.

Remove the 'french number format' validation rules for contacts

---

.travis.yml
app/concepts/access_demand/operation/import_from_ds.rb
app/concepts/access_demand/operation/import_from_signup.rb
app/concepts/csv_reader.rb
app/concepts/jwt_api_entreprise/contract/create.rb
config/initializers/access_request_import.rb
db/migrate/20200117133206_add_temp_use_case_to_jwt_api_entreprise.rb
db/migrate/20200122133628_add_demande_id_to_jwt_api_entreprise.rb
db/migrate/20200123140518_rename_jwt_demande_id.rb
db/schema.rb
spec/concepts/jwt_api_entreprise/operation/create_spec.rb
spec/controllers/jwt_api_entreprise_controller_spec.rb
spec/factories/jwt_api_entreprise.rb
spec/spec_helper.rb

Les quatre premiers commits concernent les scripts d'import des données depuis l'export des demandes réalisées dans DS et Signup. Je n'ai pas fait de specs, mais vérifié en base que tout marchait bien, et dans les trois quarts du temps j'ai fait les rapprochements à la main. Je compte bien faire un backup avant d'effectuer l'opération en prod dans tous les cas.
Le dernier commit concerne l'ajout de l'ID de la demande Signup lors de la création d'un JWT. C'est pour pouvoir rediriger l'utilisateur vers sa demande, depuis les informations de son jeton dans le dashboard ou lors du renouvellement.
1. Choisir un créneau de "maintenance". Plus de validation de demande dans Signup, de création d'utilisateurs ou de jetons ; si tout se passe bien ça ne prendra pas plus de quelques minutes. 
2. …

Alignement SIRET/cas d'usage et ID de la demande Signup 

---

app/controllers/jwt_api_entreprise_controller.rb
app/models/jwt_api_entreprise.rb
app/models/user.rb
app/serializers/contact_serializer.rb
app/serializers/jwt_api_entreprise_index_serializer.rb
app/serializers/jwt_api_entreprise_serializer.rb
app/serializers/jwt_api_entreprise_show_serializer.rb
app/serializers/user_show_serializer.rb
config/routes.rb
spec/controllers/jwt_api_entreprise_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/jwt_api_entreprise_spec.rb
spec/models/user_spec.rb
spec/support/shared_context.rb

* Ajout d'un endpoint pour servir la liste complète des JWT (uniquement pour un administrateur évidemment) ; objectifs : recherche par cas d'usage, suivi des jetons arrivant à expiration, ...
* **breaking change** dans la payload du détail d'un utilisateur, notamment la liste des JWTs lui appartenant : 
* avant : on renvoyait la liste des JWT (les clés secrètes elles même) uniquement ; comme il s'agit de JWT cela ne posait pas de problème, le front peut décoder la payload et récupérer les données du jeton (rôles d'accès, cas d'usage, date d'expiration, ...)
* maintenant : on renvoie le jeton (son hash, la clé) ainsi que les données qui y sont associées, le tout dans un "dictionnaire JSON" ; la raison initiale qui m'a poussée à faire ça c'est que j'avais besoin de renvoyer un *subject* …

JWT index et détails 

---

app/concepts/user/contract/update.rb
app/concepts/user/operation/update.rb
app/serializers/user_index_serializer.rb
app/serializers/user_show_serializer.rb
spec/concepts/user/operation/update_spec.rb
spec/controllers/users_controller_spec.rb

Renvoyer l'ID des comptes API Gouv dans les payload de données relatives aux utilisateurs (index, update, etc...) et faire en sorte que l'attribut puisse  être mis à jour.
Closes #75

Update oauth api gouv

---

app/concepts/role/operation/db_seed.rb
db/migrate/20210211122540_add_douanes_eori_role.rb
spec/concepts/role/operation/db_seed_spec.rb

Reverts etalab/admin_api_entreprise#89
on va arrêter de créer les rôles via le code mais uniquement via l'interface

Revert "[EORI] Add role"

---

spec/spec_helper.rb

Cette PR modifie [un paramètre](https://rubydoc.info/github/rspec/rspec-core/RSpec/Core/Configuration#seed-instance_method) RSpec afin de pouvoir rejouer à l'identique la suite de tests aléatoires.

chore(rspec): allow to deterministically reproduce failures

---

.rubocop.yml

Quick RuboCop's config fix as the version was upgraded.

fix(rubocop): rename `Layout/AlignParameters` cop into `Layout/ParameterAlignment`

---

.rubocop.yml
app/concepts/oauth_api_gouv/tasks/retrieve_access_token.rb
app/concepts/oauth_api_gouv/tasks/retrieve_user_info.rb
config.ru
spec/controllers/oauth_api_gouv_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/mailers/jwt_api_entreprise_mailer_spec.rb
spec/mailers/user_spec.rb
spec/rails_helper.rb

Cette PR propose d'harmoniser toute la base de code sur cette règle RuboCop :
```yaml
Style/StringLiterals:
EnforcedStyle: single_quotes
```
Commande utilisée :
```sh
bundle exec rubocop --auto-correct --only Style/StringLiterals
```

style(StringLiterals): single quotes everywhere

---

factories/jwt_api_entreprises.rb
spec/controllers/users_controller_spec.rb

Supprimer un callback dans la factory du token
Ne pas forcément entraîner la création de 4 rôles lors de la création de token, notamment pour faciliter le contrôle des données générées dans le cadre de tests unitaires.
Dans l'éventualité où plus d'un cas de test pourrait bénéficier de ce genre de création de rôle automatique, nous pourrions par la suite réintégrer un tel callback activable via un trait pour ne pas polluer les autres tests qui n'en auraient pas besoin.

refactor(factory): remove callback from jwt_api_entreprises

---

Rakefile

Je ne sais pas pourquoi ça n'a pas été fait ? Je pense que le déploiement n'était fait que sur un seul serveur.

Update Rakefile server names

---

app/concepts/jwt_api_entreprise/contract/create_magic_link.rb
app/concepts/jwt_api_entreprise/operation/create_magic_link.rb
app/concepts/jwt_api_entreprise/operation/retrieve_from_magic_link.rb
app/controllers/jwt_api_entreprise_controller.rb
app/mailers/jwt_api_entreprise_mailer.rb
app/models/concerns/random_token.rb
app/models/jwt_api_entreprise.rb
app/models/user.rb
app/policies/jwt_api_entreprise_policy.rb
app/views/jwt_api_entreprise_mailer/magic_link.html.erb
app/views/jwt_api_entreprise_mailer/magic_link.text.erb
config/environments/development.rb
config/environments/test.rb
config/routes.rb
db/migrate/20210428134253_add_magic_links_to_jwt_api_entreprise.rb
db/schema.rb
factories/jwt_api_entreprises.rb
spec/concepts/jwt_api_entreprise/operation/create_magic_link_spec.rb
spec/concepts/jwt_api_entreprise/operation/retrieve_from_magic_link_spec.rb
spec/controllers/jwt_api_entreprise_controller_spec.rb
spec/mailers/jwt_api_entreprise_mailer_spec.rb
spec/models/jwt_api_entreprise_spec.rb
spec/routing/route_spec.rb

* Génération de Magic Link envoyé par email pour partager un WT précis. 
* Récupération du JWT à partir d'un magic link. 
Les magic links sont valables pour une durée de 4h (j'ai arbitrairement choisi la durée d'expiration des sessions au dashboard, on peut en discuter/changer ici). 
@Haelle @skelz0r @cyril @hugolepetit

Magic Link for JWT

---

app/interactors/datapass_webhook/archive_previous_token.rb
app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/lib/datapass_webhook.rb
db/migrate/20210914083037_add_previous_external_id_to_authorization_requests.rb
db/schema.rb
spec/factories/datapass_webhooks.rb
spec/interactors/datapass_webhook/archive_previous_token_spec.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb
spec/lib/datapass_webhook_spec.rb

Morceau qui a été oublié de l'ancien comportement avant l'introduction des webhooks. 
Lorsqu'un événement est une validation et que la demande d'autorisation est une copie d'une ancienne demande validé, on archive le jeton associé à cette ancienne demande.

Archivage des vieux jetons

---

app/lib/omni_auth/strategies/api_gouv.rb

Try to fix 2 issues here:
1. Zeitwerk loading, which tries to infer from inflections APIGouv (in production)
2. OmniAuth provider config, which tries to infer from `:api_gouv`
ApiGouv (in dev/test)

Aliases ApiGouv with APIGouv

---

app/jobs/concerns/mailjet_helpers.rb
spec/jobs/schedule_authorization_request_mailjet_email_job_spec.rb
spec/jobs/schedule_expiration_notice_mailjet_email_job_spec.rb

Thanks to multiple errors raised from Sentry, I think the issue is to
have null values for some vars. This PR changes null values to empty
string ( '' ). It has the same behaviour for Mailjet.
Ref https://github.com/etalab/admin_api_entreprise/issues/192

Try to fix 500 errors from Mailjet

---

app/views/admin/tokens/index.html.erb
config/locales/fr.yml
spec/features/admin/token_index_spec.rb

Fix error raised when at least one token has its exp attribute to nil.
@skelz0r tu peux merge si ça te va.

Fix token index for admins

---

app/models/jwt_api_entreprise.rb
app/views/jwt_api_entreprise/_jwt_api_entreprise.html.erb
config/locales/fr.yml
db/migrate/20211210095845_add_constraint_on_exp_and_authorization_request_model_id_to_jwt_api_entreprises.rb
db/schema.rb
spec/factories/jwt_api_entreprises.rb
spec/features/admin/token_index_spec.rb
spec/features/token_details_spec.rb
spec/jobs/schedule_expiration_notice_mailjet_email_job_spec.rb
spec/models/jwt_api_entreprise_spec.rb

* `exp` ne peut pas être vide
* `authorization request` existe forcément
Fait parti du chantier de l'harden de la bdd (intégrité tout ça)
Au passage les jetons en prod qui n'avait ni `exp` ni `authorization request` ont été supprimés:
* ceux sans `exp` sont les notres, aucun intérêt vu qu'on peut les générer depuis siade
* ceux sans `authorization request` sont des relicats de duplication lors de la création du jeton (car originellement pas de vérification de l'intégrité)
Closes https://github.com/etalab/admin_api_entreprise/issues/251

Harden tokens data integrity

---

app/interactors/datapass_webhook/archive_previous_token.rb
app/interactors/datapass_webhook/create_jwt_token.rb
app/interactors/datapass_webhook/extract_mailjet_variables.rb
app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/jobs/schedule_authorization_request_mailjet_email_job.rb
config/datapass_webhooks.yml
spec/factories/datapass_webhooks.rb
spec/interactors/datapass_webhook/archive_previous_token_spec.rb
spec/interactors/datapass_webhook/extract_mailjet_variables_spec.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb
spec/interactors/datapass_webhook/schedule_authorization_request_emails_spec.rb
spec/jobs/schedule_authorization_request_mailjet_email_job_spec.rb

This PR enables the app to handle both old and new DataPass event nomenclature, which should be in production before https://github.com/betagouv/datapass/pull/213

First part of DataPass migration

---

app/interactors/datapass_webhook/find_or_create_user.rb
spec/factories/datapass_webhooks.rb
spec/interactors/datapass_webhook/find_or_create_user_spec.rb

Temporary solution (which was the case before the migration on
DataPass).
This data will be migrate soon to a specific table (for data analysis).

DataPass webhook: persists datapass' siret in User#context

---

app/views/jwt_api_entreprise/stats.html.erb
spec/features/token_stats_spec.rb

Previously was going to the logged user (i.e admin) JWT page
Now as admin, go back to the inspected user JWT page
Fix https://github.com/etalab/admin_api_entreprise/issues/288
C'est ma première PR sur ce repo donc hésitez pas à bien regarder^^

Fixed issue with back to token list on page stats

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/dsfr-extensions.scss
app/views/pages/current_status.html.erb
app/views/shared/_user_signed_in_side_menu.html.erb
app/views/shared/header/_tools.html.erb
config/locales/fr.yml

Mise à niveau graphique du header de navigation.
Pour le moment il n'y a pas de liste déroulante dans le header (j'ai tout de même demandé sur le slack du DSFr), imo c'est pas bloquant pour avancer. Ce menu déroulant aurait servi sur le hover du nom du user pour afficher un "Se déconnecter". On peut s'amuser à le coder, mais relou pour X raisons (responsive, pas accessible, etc etc..)
Au passage, n'ayant nul part l'info de l'organisation je ne peux pas l'afficher pour le moment, j'ai mis le full name en attendant. On verra quand on l'introduira.
Cette PR close 2 issues mineures qui trainaient au passage.
Des screenshots:

Enhance header

---

.rubocop.yml
.rubocop_todo.yml
app/services/status_page.rb
config/initializers/redis.rb
spec/services/status_page_spec.rb

Redis.current est deprecated et sera supprimé bientôt (et les messages d'alerte sont relous)
A la place je propose une global var dans les initializers (on fait déjà ça pour ElasticSearch). C'est pas le plus propre mais AFAIK ça devrait rien changer de l'actuel.
Attention j'ai zéro experience avec Redis donc reviewez prudemment...

Replacing Redis.current (deprecated)

---

config/locales/fr.yml

Ajoute notamment une référence aux CGU et un lien.
Cette PR fait suite au changement de libellé du bouton : https://github.com/etalab/admin_api_entreprise/pull/321#event-6068116965

Message d'alerte de transmission du jeton plus explicite

---

app/models/access_log.rb
db/migrate/20220111162835_create_access_logs.rb
db/schema.rb

Cette PR introduit uniquement une table dans en base pour y stocker les logs d'accès. L'objectif est de tester les visualisations dans metabase qui sera dans un premier temps l'unique point d'entré à ces données. 
Une fois déployé en sandbox j'y importe les logs issus de Elasticsearch. 
Suite et industrialisation : 
* création du modèle dans l'application Rails avec liens relationnels  
* script d'export/import de Elasticsearch vers cette table PG

Introduce table to store access logs

---

config/locales/fr.yml

Parler de demande initiale ou d'habilitation plutôt que Datapass qui est un terme interne.

Change le label de la demande Datapass dans le dashboard

---

config/endpoints/1_insee_etablissements.yml

Retire les mentions qui indiquait que l'adresse est dans un autre endpoint. Ainsi que les infos de l'unité légale.

MAJ suite ajout de l'adresse et unite legale

---

app/views/endpoints/show.html.erb
config/locales/fr.yml

- Passe en H6 les titres vraiment de second plan
- Déplace l'ouverture des données au niveau des conditions d'utilisation
- Crée un titre cgu.endpoint.opening.title

Modifie Layout fiche métier 

---

config/endpoints/10_dgfip_chiffres_affaires.yml
config/endpoints/13_dgfip_liasses_fiscales.yml
config/endpoints/14_dgfip_attestation_fiscale.yml
config/endpoints/15_urssaf_attestation_sociale.yml
config/endpoints/16_msa_conformites_cotisations.yml
config/endpoints/17_probtp_conformites_cotisations_retraite.yml
config/endpoints/18_fntp_cartes_pro_travaux_publics.yml
config/endpoints/19_cnetp_attestations_cotisations_conges_payes_chomage_intemperies.yml
config/endpoints/1_insee_unites_legales.yml
config/endpoints/22_qualibat_certifications_batiment.yml
config/endpoints/24_inpi_brevets.yml
config/endpoints/25_inpi_marques.yml
config/endpoints/26_inpi_modeles.yml
config/endpoints/2_infogreffe_mandataires_sociaux.yml
config/endpoints/3_insee_adresse_etablissement.yml
config/endpoints/3_insee_siege_social.yml
config/endpoints/4_ministere_interieur_rna.yml
config/endpoints/5_inpi_actes.yml
config/endpoints/6_fabnum_conventions_collectives.yml
config/endpoints/7_cmafrance_rnm.yml
config/endpoints/9_douanes_eori.yml

Première relecture après création des fiches métiers.
- Cette PR transforme aussi tous les titres intermédiaires auparavant en gras, en utilisant un `<h6>`
- Elle retire également les `&apos;` dans les clés de type "texte court", qui apparaissait en html sur l'interface

Relecture des fiches métiers ajoutée dans lindex v3

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb

Le premier qui passe peut merger imo.
Closes https://github.com/etalab/admin_api_entreprise/issues/386

DatapassWebhook::FindOrCreateAuthorizationRequest saves siret from webhook

---

Gemfile
Gemfile.lock

The commit 229ddea17674f9178ebf48f8cee7d2d6b82b6c70 introduces a bug on
Passenger:
```
App 2590953 output: Error: The application encountered the following
error: You have already activated strscan 3.0.1, but your Gemfile
requires strscan 3.0.3. Since strscan is a default gem, you can either
remove your dependency on it or try updating to a newer version of
bundler that supports strscan as a default gem. Gem::LoadError)()
```
A (temporary) workaround is to fix strscan to 3.0.1.
The issue seems to be this one:
https://github.com/phusion/passenger/issues/2409
According to these issues, the best workaround is to use
`PassengerPreloadBundler` in order to load right versions of gems.
Ref https://github.com/phusion/passenger/issues/2410#issuecomment-1011906640

FIX Passenger issue with strscan

---

config/deploy.rb

Comme pour les autres applications Rails, on bénéficie des [améliorations](https://github.com/etalab/very_ansible/pull/91) côté Ansible/Samhain pour simplifier la tâche de mise à jour de base Samhain. Elle est aussi plus efficace comme ça pour éviter les faux positifs.

Simplification et amélioration de la mise à jour de base Samhain

---

app/models/endpoint.rb
app/views/endpoints/show.html.erb
config/locales/fr.yml
spec/features/endpoints/show_spec.rb
spec/models/endpoint_spec.rb

Ces erreurs sont propulsés à l'aide du fichier swagger (et sera donc toujours à jour avec le code en production).
Deux exemples: https://sandbox.dashboard.entreprise.api.gouv.fr/endpoints/urssaf/attestation_sociale et https://sandbox.dashboard.entreprise.api.gouv.fr/endpoints/insee/unites_legales
Chaque endpoint possède des erreurs
Il faut affiner les wordings et potentiellement l'UI.

Ajout des erreurs sur les fiches métiers

---

app/views/endpoints/_endpoint.html.erb
app/views/endpoints/show.html.erb
config/locales/endpoint.fr.yml

- Retirer l'icône quand la donnée est ouverte afin que l'utilisateur repère en un coup d'oeil la donnée protégée.
- Change le terme "publiques" par "ouvertes" ... publiques pouvant être confondu avec "du service public"

Retire l'icone des données ouvertes et change le label

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
spec/organizers/datapass_webhook/api_particulier_spec.rb

Avoid to fail on contact creation because of contact metier missing
(does not exist on this API)

DatapassWebhook::APIParticulier does not have a contact_metier

---

config/locales/fr.yml

Les questions de la FAQ ne s'ouvrent pas automatiquement, il est donc difficile d'accéder au lien de la visio.  En attedant de résoudre le problème, cette PR propose de mettre le lien direct sur le bandeau

Ajoute lien vers la visio

---

config/locales/faq_entries.fr.yml
config/locales/fr.yml

Cette PR vise à réduire le contenu affiché dans la pop up de transfert de jeton, en basculant une partie du contenu dans la FAQ.
J'ai glissé un commit de wording.

Réduit le contenu de la pop up de transfert du jeton

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/models/authorization_request.rb
app/organizers/datapass_webhook/api_entreprise.rb
app/organizers/datapass_webhook/api_particulier.rb
db/migrate/20220908134459_add_api_to_authorization_requests.rb
db/schema.rb
spec/organizers/datapass_webhook/api_entreprise_spec.rb
spec/organizers/datapass_webhook/api_particulier_spec.rb

Plus simple pour faire les disjonctions que de passer par les scopes de jetons.
Post merge de cette PR, on pourra migrer tous les existants (impossible en l'état car des jetons n'ont pas de scope related https://github.com/etalab/admin_api_entreprise/issues/684 donc impossible de savoir avec la db) et mettre une contrainte sur le champ.
On pourra aussi flip/harden le `Token#api`

Ajout d'un champ API aux demandes Datapass

---

spec/features/api_entreprise/faq_spec.rb

@skelz0r je bloque un peu là dessus
=> problème en local, le navigator.clipboard n'est pas accessible depuis qu'on a changé les URL, donc les ancres ne copient pas correctement
(probablement du au fait qu'on est pas en HTTPS)
Et le test ne fonctionne pas...
Si jamais tu as une idée

Tests tooltips

---

config/i18n-tasks.yml
config/locales/api_entreprise/fr.yml

Suite au problème de cookie de tout à l'heure, je me rend compte que le flash message qui s'affiche en cas d'utilisateur inconnu ou en cas d'erreur indéterminée n'existe pas
Cette PR les rajoute

Fixed translation missing in case of failed authentication

---

app/lib/seeds.rb

Previously we destroy AuthorizationRequests before Tokens Then tokens end up without authorization_request_model_id and we get an error

Fix flushdb bug

---

app/controllers/api/datapass_webhooks_controller.rb
spec/controllers/api/datapass_webhooks_controller_spec.rb

This reverts commit f553cc9392460451a8c227f305d1c0c49e6af764.
Logs less data, only datapass id/event.
Ref https://github.com/etalab/admin_api_entreprise/issues/699

Revert "No more tracking on Sentry for incoming DataPass webhooks"

---

app/views/shared/api_entreprise/header/_menu.html.erb
config/locales/api_entreprise/fr.yml

- Déplace la bannière sous la barre de navigation / cf dsfr
- Un message légèrement différent selon l'espace concerné :
**Espace développeur et guide de migration** : Parle spécifiquement de migration 
**Ailleurs sur le site** : Message plus court, annonce la nouvelle version de l'API

Bannière bureau ouvert

---

config/deploy.rb

En lien avec la séparation des applications et la gestion des permissions via Ansible avec les listes de contrôle d'accès (ACL) Unix.

Suppression tâche 'ownership' du déploiement et éléments associés

---

config/endpoints/14_dgfip_attestation_fiscale.yml

Suite à cette discussion : 
https://3.basecamp.com/4318089/buckets/26509199/documents/5438355608#__recording_5517058139

Attestation fiscale - Précise le cas des BIC BNC et BA

---

app/assets/stylesheets/commons.scss
app/controllers/api_entreprise/stats_controller.rb
app/controllers/api_particulier/stats_controller.rb
app/views/api_entreprise/stats/index.html.erb
app/views/api_particulier/stats/index.html.erb
bin/deploy-sandbox
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
spec/features/api_entreprise/stats_spec.rb
spec/features/api_particulier/stats_spec.rb

Il a été demandé qu'on remette une page de stats
Je n'ai pas réussi à avoir une iframe sans scroll bar...
Et je ne suis pas certain que mon tests soit des plus utile... J'aurai voulu testé le contenu de l'iframe mais sans succès 
Déployé ici : 
- https://sandbox.entreprise.api.gouv.fr/stats
- https://sandbox.particulier.api.gouv.fr/stats

Add /stats for API Entreprise/Particulier

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
spec/factories/authorization_requests.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb
spec/organizers/datapass_webhook/api_entreprise_spec.rb
spec/organizers/datapass_webhook/api_particulier_spec.rb

Old version did not manage when there's already a user with the same email persisted.
Ref https://github.com/etalab/admin_api_entreprise/issues/1090

Harden contacts creation on datapass webhooks

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/models/user.rb
spec/models/user_spec.rb

Sometimes DataPass webhooks contains email with unclean emails (with uppercase or extra spaces), this commit normalize and harden email management.
Closes https://github.com/etalab/admin_api_entreprise/issues/1090

Harden email management on creation through DataPass

---

app/services/open_bureau_date.rb

Time.parse uses system clock for the timezone. If the system clock has a different timezone from our servers clock, the test will fail.
It is more resilient to instead use String#in_time_zone to rely on Rails set timezone instead of the computer's clock.

Fix annoying timezone bug

---

db/migrate/20230623074703_remove_scopes_tables.rb
db/schema.rb

Add if_exists constraint because `scopes` table exists in production (but not in local), which is strange because aa2aa7986098f65d5dca8884ec32e97bcfe432f6 already cleaned it.
It's not a big issue, no need to be conscious about this.
Closes https://github.com/etalab/admin_api_entreprise/issues/1104

Clean scopes tables

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml

Précise que le QF par défaut est celui du mois en cours et ajoute FAQ : <img width="725" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/64324ac7-77b6-491e-9fe8-726d546d5fe0">

[API Particulier] Documentation sur la date du QF et la date de calcul du QF

---

app/controllers/concerns/sessions_management.rb
app/views/api_entreprise/pages/home.html.erb
app/views/api_particulier/pages/home.html.erb
app/views/shared/api_entreprise/header/_tools.html.erb
app/views/shared/api_particulier/header/_tools.html.erb
app/views/shared/pages/_home_alerts.html.erb
config/i18n-tasks.yml
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
spec/features/api_particulier/logout_spec.rb

Have to update MonComptePro configs with the new post logout redirect uris, which are domains with /compte/apres-deconnexion path: already done on tests, have to be done on staging and production (currently empty btw).
Moreover:
* We use a /compte/apres-deconnexion in order to keep a single entry for MonComptePro (no more update here), we can do whatever we want here
* Have to stub the actual method for the redirect: indeed, it's the browser which make the redirect, we can't use webmock here
Closes https://github.com/etalab/admin_api_entreprise/issues/707

Introduce proper logout on MonComptePro

---

app/controllers/api_entreprise/stats_controller.rb
app/controllers/api_particulier/stats_controller.rb
spec/controllers/api_entreprise/stats_controller_spec.rb
spec/controllers/api_particulier/stats_controller_spec.rb

Related https://mattermost.incubateur.net/betagouv/pl/docwf68bztfnbgejbkurcneowc

Introduce /stats.json

---

app/assets/stylesheets/api_entreprise.scss
app/assets/stylesheets/api_particulier.scss
app/assets/stylesheets/dsfr-corrections.scss

We can't easily target p before ul because
it is generated by markdown_to_html
DSFR defaults to a big margin under p, we can't
target p before ul (https://stackoverflow.com/a/1132370/5372951) so instead we apply negative margin to any ul immediatly after p
slightly hacky but should work well
@skelz0r Je suis pas certain d'où mettre cette correction, aucun fichier ne me semble convenir donc j'ai crée un dsfr-corrections

Fixing margin for paragraphs right before lists

---

config/routes.rb
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
spec/features/api_entreprise/signin_process_datapass_spec.rb
spec/features/api_particulier/signin_process_datapass_spec.rb

Previous test config was misconfigured, it was the error associated to an unknown user, which is not correct for this scenario.
Ref https://github.com/etalab/admin_api_entreprise/issues/1134

Harden OmniAuth failure management

---

app/interactors/user/find_or_create_through_oauth.rb
app/lib/omni_auth/strategies/api_gouv_abstract.rb
spec/features/api_entreprise/signin_process_datapass_spec.rb
spec/features/api_particulier/signin_process_datapass_spec.rb
spec/organizers/api_entreprise/user/oauth_login_spec.rb
spec/organizers/api_particulier/user/oauth_login_spec.rb

This field is not required by us and will be remove in near future from our provider (MonComptePro).

Remove phone_number from user creation from OAuth login

---

app/interactors/token/retrieve_expiring.rb
app/jobs/token_expiration_notice_job.rb
spec/jobs/token_expiration_notice_job_spec.rb

TokenExpirationNoticeJob can't send more than one email by batch
Thanks to:
1. Reorder of the scheduling
2. Test on min element of already sent emails
It is impossible to send more than one email by batch on a specific
token.
Closes https://linear.app/pole-api/issue/API-1055/harden-la-gestion-des-relances-sur-les-expirations

TokenExpirationNoticeJob can't send more than one email by batch

---

app/views/shared/pages/redoc.html.erb

Make API CAF v1 still available, even if deprecated: it's not the same logic as API Entreprise which has a lot of deprecated endpoints, but new version incrementaly enhanced.
Related https://github.com/etalab/admin_api_entreprise/pull/1087

API Particulier: swagger shows deprecated endpoints

---

db/migrate/20230922102926_revoking_not_used_authorization_request_with_no_datapass.rb
db/schema.rb

Les ids des actifs ont été récupéré sur metabase via la request : 
```
SELECT 
ar.id
FROM 
authorization_requests ar
INNER JOIN 
tokens t on ar.id = t.authorization_request_model_id
INNER JOIN
access_logs al on al.token_id = t.id
WHERE 
ar.external_id IS NULL
AND
al.timestamp > (CURRENT_DATE - INTERVAL '3 months')
GROUP BY ar.id
```

Revoke inactive Authorization Request without Datapass

---

app/assets/stylesheets/components/api_status.scss
app/models/abstract_endpoint.rb
app/views/api_entreprise/endpoints/_details.html.erb
app/views/api_particulier/endpoints/_details.html.erb
config/endpoints/api_entreprise/15_urssaf_attestation_vigilance.yml
config/endpoints/api_entreprise/1_insee_etablissements.yml
config/endpoints/api_entreprise/3_insee_adresse_etablissement.yml
config/endpoints/api_entreprise/3_insee_siege_social.yml
config/endpoints/api_entreprise/3_insee_unites_legales.yml
config/endpoints/api_particulier/cnaf_quotient_familial.yml
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml
spec/features/api_entreprise/endpoints/show_spec.rb
spec/features/api_particulier/endpoints/show_spec.rb
spec/rails_helper.rb

Implement for both API Particulier (caf v1) and API Entreprise (INSEE Sirene)
More to come later
Closes https://linear.app/pole-api/issue/API-1174/integrer-le-statut-de-lapi-sur-la-page-du-catalogue

Introduce real time status on endpoints

---

app/services/token_export.rb
spec/services/token_export_spec.rb

Petit edit par rapport au contenu du ticket : 
On abandonne le chiffrage, les fichiers seront distribués de facon sécurisé via <insérer une solution pour le nous du futur>.
Le script est à run une seule fois, donc est jetable, donc rien n'est réutilisable, c'est fait exprès. J'suis pas hyper fan du naming du fichier, mais à priori on va le jeter une fois que c'est fait donc j'ai flemmé là dessus.
L'utilisation se fait direct en console.
On peut binomer pour aller plus vite.

Export legacy token to file

---

app/lib/seeds.rb
app/models/authorization_request.rb
app/models/token.rb
db/migrate/20231010150356_token_add_blacklisted_at.rb
db/schema.rb
db/seeds.rb
lib/tasks/token.rake
spec/factories/tokens.rb
spec/interactors/datapass_webhook/revoke_current_token_spec.rb
spec/organizers/token/send_expiration_notices_spec.rb

Première partie de l'utilisation du nouveau champ `blacklisted_at`.
La très bonne pratique aurait voulue que je continue d'écrire sur les 2 colonnes en même temps, mais bon ... voilà (ceci est un argument)
En follow up : 
- Une PR sur siade pour utiliser ce champs à la place du champ blacklisted
- Une PR sur admin pour changer la tache rake et mettre le blacklisting à +1 mois
- Une PR sur admin pour retirer les champs blacklisted et archived

Ajout et utilisation de la colonne blacklisted_at

---

app/interactors/datapass_webhook/revoke_current_token.rb
app/models/authorization_request.rb
db/migrate/20231012152426_migrate_blacklisted_authorization_request_to_revoked.rb
db/schema.rb
spec/interactors/datapass_webhook/revoke_current_token_spec.rb

C'est un brainfart parce qu'on a rien qui gère dans le code les AR en status 'blacklisted'. C'est juste qu'entre le blacklist du token et le revoke de l'authorization request on mélangeais les termes.
Du coup en db on a des status revoked et des status blacklisted. On a dit qu'on ne conservait que les status qui était des states lié à datapass. Revoked it is donc.
Au moins c'est clair now

Updating Authorization Request on revoke event

---

app/controllers/api_particulier/new_tokens_controller.rb
app/services/token_export.rb
config/routes/api_particulier.rb
spec/controllers/api_particulier/new_tokens_controller_spec.rb

Cette PR est dans la foulée de la PR de génération des fichiers.
Il fallait fournir une url unique pour N user cachée, derrière un login MCP qui renvoit le premier fichier matchant la nomenclature.
À jeter une fois que la migration des tokens sera terminée

Provide Standard URL for new token file

---

config/environments/test.rb

```
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead.
```

Remove deprecated message due to Rails 7.1

---

app/assets/stylesheets/shared/pages/home/_section_demonstrateur.scss
app/views/api_entreprise/pages/home/_section_developers.html.erb
app/views/api_entreprise/pages/home/_section_howto.html.erb
app/views/api_entreprise/pages/home/_section_partners.html.erb
app/views/api_entreprise/pages/home/_section_welcome.html.erb
app/views/api_entreprise/pages/newsletter/_banner.html.erb
app/views/api_particulier/pages/home.html.erb
app/views/api_particulier/pages/home/_section_demonstrateur.html.erb
app/views/api_particulier/pages/home/_section_developers.html.erb
app/views/api_particulier/pages/home/_section_partners.html.erb
app/views/api_particulier/pages/home/_section_welcome.html.erb
config/locales/api_particulier/fr.yml

Ajout d'un section en page d'accueil :

[API Particulier] Ajoute section demonstrateur en page d'accueil

---

app/controllers/api_entreprise/attestations_controller.rb
app/policies/token_policy.rb
app/views/shared/authorization_requests/show.html.erb
config/locales/api_entreprise/fr.yml
spec/features/api_particulier/authorization_request_spec.rb

Petit point : Je pense qu'il y a un refacto à faire sur l'ensemble du sujet attestation. Notament parce que désormais le point d'entrée c'est l'habilitation et non le menu et donc il faudrait que la page des attestations ne permette plus de choisir le token (ou à minima le pré-sélectionne). Et il y a pas mal de complexité inutile dans la facade et la policy.
Il y a aussi un travail de clean parce que pas mal de code existant n'est plus nécessaire dans cette nouvelle interface.
Cependant, étant donné que l'ancienne interface existe encore tant qu'on ne fait pas le remplacement, j'ai choisi de ne pas faire ce clean qui prendrais du temps maintenant alors qu'une fois le switch fait, il suffira d'appuyer sur delete.
Un ticket a été crée à ce sujet dans le projet linear.

AuthorizationRequest: show - Added attestation block

---

app/views/api_particulier/endpoints/show.html.erb
config/locales/api_particulier/fr.yml

[Erreur contenu] Mise en exuergue API depréciée : Retire mention doc API Entreprise

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb

For API Particulier, we only sent webhooks for validated event, so every validated API Particulier authorization request has no first_submitted_at set, which leads to a bug for end user on their account (no tokens).

DataPass webhooks: set first_submitted_at for any non-draft event

---

app/mailers/api_entreprise/user_mailer.rb
app/views/api_entreprise/user_mailer/notify_datapass_for_data_reconciliation.html.mjml
app/views/api_entreprise/user_mailer/notify_datapass_for_data_reconciliation.text.erb
spec/mailers/api_entreprise/user_mailer_spec.rb

We don't have good DB integrity on authorization_request_id which supposedly represents datapass ID for the AuthorizationRequest.
Will use external_id instead.

Fix notify_datapass_for_data_reconciliation

---

lib/tasks/token.rake

Forcément le seul point d'entré qui n'était pas testé.

Fixed typo in rake task token:mark_as_migrated

---

app/controllers/api_particulier/authenticated_users_controller.rb
app/controllers/api_particulier_controller.rb
app/views/shared/api_particulier/_containerized_body.html.erb
spec/features/api_particulier/faq_spec.rb

Error occured when an authenticated user would open non authenticated APIPart pages

Fixing regression on APIPart templates

---

app/views/api_entreprise/authorization_request_mailer/_block_help_demande.html.mjml
app/views/api_entreprise/token_mailer/expiration_notice_0J.mjml
app/views/api_entreprise/token_mailer/expiration_notice_15J.mjml
app/views/api_entreprise/token_mailer/expiration_notice_30J.mjml
app/views/api_entreprise/token_mailer/expiration_notice_60J.mjml
app/views/api_entreprise/token_mailer/expiration_notice_7J.mjml
app/views/api_entreprise/token_mailer/expiration_notice_90J.mjml
app/views/api_entreprise/token_mailer/magic_link.html.mjml
app/views/api_particulier/authorization_request_mailer/_block_help_demande.html.mjml
app/views/api_particulier/authorization_request_mailer/_enquete_satisfaction.html
app/views/api_particulier/authorization_request_mailer/embarquement_valide_to_demandeur_is_tech.html.mjml
app/views/api_particulier/token_mailer/expiration_notice_0J.mjml
app/views/api_particulier/token_mailer/expiration_notice_15J.mjml
app/views/api_particulier/token_mailer/expiration_notice_30J.mjml
app/views/api_particulier/token_mailer/expiration_notice_60J.mjml
app/views/api_particulier/token_mailer/expiration_notice_7J.mjml
app/views/api_particulier/token_mailer/expiration_notice_90J.mjml
app/views/api_particulier/token_mailer/magic_link.html.mjml
config/locales/mailers.fr.yml
spec/mailers/api_entreprise/token_mailer_spec.rb
spec/mailers/api_particulier/token_mailer_spec.rb

@Samuelfaure c'est prêt, j'ai fini ma relecture. 
Par contre, il va y avoir du changement concernant les mails de transferts de compte. ça concerne : 
[notify_datapass_for_data_reconciliation](http://entreprise.api.localtest.me:5000/rails/mailers/api_entreprise/user_mailer/notify_datapass_for_data_reconciliation)
[transfer_ownership](http://entreprise.api.localtest.me:5000/rails/mailers/api_entreprise/user_mailer/transfer_ownership)
C'est en cours dans [cette PR ](https://github.com/etalab/admin_api_entreprise/pull/1354) mais je pense qu'on peut merger

Api 1599 relecture mails api part

---

app/views/api_entreprise/authorization_request_mailer/_list_scopes.html.mjml
spec/mailers/api_entreprise/authorization_request_mailer_spec.rb

fix https://linear.app/pole-api/issue/API-1780/bug-scopes-sur-mail-embarquement
Je suis pas certain de vouloir conditionner l'affichage du partial scopes à l'existence d'un token parce que NORMALEMENT on affiche la liste des scopes seulement dans les mails où un token a été généré.
D'un autre coté c'est plus safe comme ça si pour une raison ou une autre le token a pas encore été généré. Whatever.

Fixed scopes trying to display when no token

---

config/i18n-tasks.yml
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml

Ça redirige toujours vers la homepage quand on tente d'accéder à une ressource inexistante à cause de ce bout de code dans application_controller.rb:
```ruby
rescue_from ActiveRecord::RecordNotFound do |_|
error_message(title: t('.error.record_not_found'))
if user_signed_in?
redirect_current_user_to_homepage
else
redirect_to_root
end
end
```
On pourrait changer ça sur l'app entière mais la flemme et possibles effets de bord relou.
A minima fix le message, quickwin.

error message when trying to access non-existent API

---

app/models/abstract_endpoint.rb
app/views/api_entreprise/endpoints/show.html.erb
app/views/api_particulier/endpoints/show.html.erb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml
spec/features/api_entreprise/endpoints/show_spec.rb
spec/features/api_particulier/endpoints/show_spec.rb
spec/models/api_entreprise/endpoint_spec.rb
spec/models/api_particulier/endpoint_spec.rb

Ça fonctionne sauf pour certains repos dans siade_staging_data où on a écrit "diffusable" au lieu de "diffusible" - je vais faire une PR pour corriger ça.
Je met ça là pour le moment, à voir si @DorineLam veut changer à son retour :

Link to github test cases

---

app/views/api_particulier/endpoints/_details.html.erb
app/views/api_particulier/endpoints/_endpoint.html.erb
config/endpoints/api_particulier/cnaf_msa_complementaire_sante_solidaire.yml
config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/endpoints/api_particulier/cnous_student_scholarship.yml
config/endpoints/api_particulier/education_nationale_statut_eleve.yml
config/endpoints/api_particulier/mesri_student_status.yml
config/endpoints/api_particulier/pole_emploi.yml
config/endpoints/template.particulier.yml.example
config/locales/api_particulier/fr.yml

- Ajoute lien vers le guide
- Ajoute picto FC
- Ajoute les modalités d'appel sur les cartes du catalogue : https://linear.app/pole-api/issue/API-2158/afficher-les-modalites-dappel-sur-les-cartes-api-du-catalogue

Met en avant la modalité d'appel FranceConnect dans le catalogue et la fiche métier - API-2158 et API-660 

---

spec/features/prolong_token_build_spec.rb

Sometimes execution could lead to 1 second diff during execution. Froze time during test execution to match correct behavior without luck
Vu dans l'execution des tests ici : https://github.com/etalab/admin_api_entreprise/actions/runs/8042944900/job/21967165344

Fixing flaky test on prolong suite

---

db/migrate/20221025080557_initial_schema.rb

Skip access_logs for production, created with ansible
Ref https://github.com/etalab/admin_api_entreprise/pull/1475

Harden initial db creation for production

---

config/locales/api_particulier/documentation.fr.yml

- Préciser que le recipient n'est pas obligatoire sur toutes les API

Modification doc Recipient

---

app/models/authorization_request.rb
app/models/token.rb
spec/models/authorization_request_spec.rb

1. Destroy N-N association user_authorization_request_roles
2. Destroy magic links linked to tokens
3. Destroy token: token can't be orphan

Harden destroy behaviour of AuthorizationRequest

---

config/routes/api_entreprise.rb
config/routes/api_particulier.rb
config/seo/api-entreprise/robots.txt
config/seo/api-particulier/robots.txt
config/seo/robots.txt

URI.open renders a 500 error in dev. Keep it simple and shared (apps are iso now).

Simplify and fix robots.txt

---

app/lib/authorization_request_condition_facade.rb
config/datapass_webhooks_entreprise.yml
config/datapass_webhooks_particulier.yml
spec/lib/authorization_request_condition_facade_spec.rb

Previous version did not send validation emails to contacts if demandeur is different from metier, and metier is the same as technique.
This commit groups this case above with the 3 distincts emails.
Ref https://mattermost.incubateur.net/betagouv/pl/s3mwaj1muifepp7wtc4spsxcwc

Validation mailing: group similar cases

---

app/lib/seeds.rb

Destroy ProlongTokenWizard records before flushing as to avoid foreign key constraint issues while seeding
C'est pas le commit le plus elegant mais OSEF KISS

Harden seeds

---

app/controllers/api_particulier/endpoints_controller.rb
app/models/abstract_endpoint.rb
config/endpoints/api_particulier/cnaf_quotient_familial.yml
config/locales/api_particulier/fr.yml
spec/features/api_particulier/endpoints/index_spec.rb

We only have CNAF QFv1 and we want it back, but
keeping the "deprecated" tag

Deprecated APIs are back in catalogue

---

config/locales/api_particulier/documentation.fr.yml

Added specific section for cache

---

app/helpers/external_url_helper.rb
spec/helpers_spec/external_url_helper_spec.rb

Will be use to handle disjonction between data provider for the redirection between v1->v2.

Use a custom url for each data provider for datapass_reopen_authorization_request_url

---

config/locales/api_particulier/fr.yml

Seul éventuel soucis c'est que c'est un peu confusant pour les users de qfv1.
Mais bon vu qu'elle est déprécié IMO osef.

Replacing CNAV by CNAF & MSA label in qf scopes

---

app/controllers/api/datapass_webhooks_v2_controller.rb
app/controllers/concerns/datapass_webhooks.rb
app/interactors/datapass_webhook/adapt_v2_to_v1.rb
app/interactors/datapass_webhook/extract_mailjet_variables.rb
app/organizers/datapass_webhook/v2/api_entreprise.rb
app/organizers/datapass_webhook/v2/api_particulier.rb
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
spec/controllers/api/datapass_webhooks_v2_controller_spec.rb
spec/factories/datapass_webhooks_v2.rb
spec/interactors/datapass_webhook/extract_mailjet_variables_spec.rb
spec/organizers/datapass_webhook/v2/api_entreprise_spec.rb
spec/organizers/datapass_webhook/v2/api_particulier_spec.rb
spec/support/shared_examples/datapass_webhooks.rb

NYI in DataPass v2.
We use an adapter to keep this PR small and reuse v1 format, thanks to the iso aspect.
Full ~iso with v1, will be some iteration to add more data (like the `data` key within the example payload below), in order to handle future `modalities` ( ref https://github.com/etalab/data_pass/pull/237 ))
Ref https://gist.github.com/skelz0r/07d6a797804652f5b2496897d124820a

Introduce DataPass webhooks v2

---

app/views/shared/authorization_requests/index.html.erb

`viewable_by_users` includes archived authorization requests, did not have a required token in that state (we can go from draft to archived)
Closes https://errors.data.gouv.fr/organizations/sentry/issues/137139/

Bugfix: try to displays archived authorization token

---

app/models/api_entreprise/endpoint.rb

We expect a hash to call "stringify_keys",
or raise if nil (when value is absent).
I18n returns "Translation missing" string if absent, which isn't caught by "nil?" and errors with "stringify_keys".

Fix error when endpoint missing

---

config/endpoints/api_particulier/cnaf_quotient_familial.yml

L'API n'a été mise en production qu'en mai 2024 au lieu de janvier 2024. On a donc décidé de repousser la fin de la distribution de l'API à mai 2025 pour laisser un an aux éditeurs/FS de faire la bascule. Dans l'infolettre envoyée en mai pour annoncer la v2, j'ai annoncé mai comme fin de distribution de l'API. 
(Délai qu'il faudrait peut être revoir au regard des problèmes d'identification des usagers dans la nouvelle API)

Modification date de fin de distribution de l'API

---

config/locales/api_particulier/fr.yml

Scope were not displayed in the BO because the translation did not exist

Adding CNAV scopes translations

---

.github/workflows/ci_cd.yml

This reverts commit 7b81a0b4d2aa843495f1bd9396309c11fcc4a8b9.
This was desirable after all, brakeman is useless for dependabot and simplecov can simply not be run by the integrator.

Revert "running all tests on dependabot prs"

---

config/endpoints/api_particulier/pole_emploi.yml

API Paiement FranceTravail : mieux mettre en avant le fait de vérifier le lien entre identité du particulier et identifiant

---

config/endpoints/api_entreprise/carif_oref_certifications_qualiopi_france_competences.yml

Le mot "Qualiopi" était inscrit 2 fois .

API-3675 Supprimer le mot "qualiopi" inscrit 2 fois

---

app/views/shared/tokens/_detail.html.erb
app/views/shared/tokens/_detail_short.html.erb
spec/features/api_particulier/authorization_request_show_spec.rb

Not really important, confuse users, so flip it

Remove token ids from dashboard view

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/endpoints/api_particulier/cnous_student_scholarship.yml

Suite à mon point avec le CNOUS le 11.10, j'ai modifié la doc pour : 
- ajouter de nouvelles régions pour les bourses sanitaires et sociales (et retirer la région Normandie, qui n'est pas inclus)
- retirer les DROM dans les territoires que couvre l'API (pas encore conventionnés donc non inclus)
- supprimer la mention qui dit que ça n'inclut que les boursiers français : pas de distinction de nationalité, tant qu'ils ont une bourse gérée par le CNOUS ou une bourse régionale, ils sont inclus. J'ai modifié en mettant que ça n'intègre pas les bourses étrangères (même ceux de l'UE). ça me paraît évident, mais sait on jamais.

[API Statut étudiant boursier] Correction de la documentation

---

db/schema.rb

Pour éviter de casser le schéma de table mis en place côté système.
Dans l'état actuel, le déploiement des recettes Ansible pour cette application est cassé à cause de ça.

schema : évite de supprimer access_logs si elle existe déjà

---

config/endpoints/api_particulier/education_nationale_statut_eleve.yml

@DorineLam preneuse de ton point de vue 
Il faudrait modifier la doc métier de l'API élève scolarisé et boursier pour préciser qu'il n'y a plus la bourse. La bourse devrait être réintégré dans l'API courant 2025
- je retire toute mention de la bourse dans la doc métier
ou 
- je mets juste une alerte au début de la doc pour prévenir qu'on ne délivre plus le statut boursier
Je suis plutôt pour la 2ème option pour que les FS puissent quand même se documenter sur la notion de bourse (mise à jour, bascule d'année etc.)/se projeter mais tu as peut être un avis différent ?
Ici une proposition avec la 2ème option.

Préciser que l'API ne délivre plus notion de bourse

---

config/endpoints/api_entreprise/dgfip_liens_capitalistiques.yml

@skelz0r, j'ai restructuré la doc, en espérant ne pas avoir transformer le sens.
- De ce que je lisais il y avait des éléments dans la partie périmètre qui concernait la partie données et quelques répétitions. 
- J'ai essayé de regrouper les informations dans des blocs parents pour faciliter la lecture.
- J'ai aussi créé des liens vers la FAQ pour alléger la partie principale.
- Je pense qu'il y a des infos concernant des clés en particulier qu'on pourrait basculer dans la doc du swagger pour alléger. Je vais faire une PR et on élaguera après.

API Liens capitalistiques : Restructure contenu liasses fiscales

---

app/views/api_entreprise/endpoints/_use_cases.html.erb
app/views/api_particulier/endpoints/_use_cases.html.erb
config/endpoints/api_entreprise/dgfip_liens_capitalistiques.yml
config/locales/api_entreprise/cas_usages_entries.fr.yml
config/locales/api_entreprise/fr.yml

Closes https://linear.app/pole-api/issue/API-4337
Closes https://linear.app/pole-api/issue/API-4340

Add use cases/label for Liens Capitalistiques

---

Gemfile
Gemfile.lock

During deployment, when bundler is installing or updating gems, it might be trying to activate different versions of the uri gem. The error message shows uri 1.0.2 (base version from our Ruby version) is activated but the Gemfile requires uri 1.0.3
there's a version conflict between what's already loaded and what bundler wants to load.
Other solution: update deployment process to include bundle clean --force

Fix URI gem version

---

app/models/abstract_endpoint.rb
spec/models/api_particulier/endpoint_spec.rb

This only impacts API Particulier.
All api part v3 endpoint are prefixed with the [modality] This PR removes from the title the modality to have a better display.
This is a temporary fix to enhance display waiting for more adaptation to the api part v3 swagger format

Removing modality from catalogue titles

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial.yml

@Miryad3108 maintenant qu'on est passé en V3, il me semble que ça n'a plus de sens de garder la mention "nouvelle version"

Retire tag novelty de l'API QF

---

Gemfile
Gemfile.lock

jwt major bump breaks everything, fix it to 2.x
Ref https://github.com/etalab/admin_api_entreprise/pull/1917

Bump production dependencies

---

app/controllers/admin/tokens_controller.rb

Can't use distinct because of the join which built a sql query with a group by (incompatible with a top level distinct)
`uniq` is good enough

Admin tokens: display only one token
