config/routes.rb
config/schedule.yml

* Changement de l'URL de la Web UI de Sidekiq
* Configuration des tâches automatiques de Sidekiq CRON pour les environnements de sandbox et de production

Fix au déploiement en sandbox de la fonctionnalité de notifications d'expiration des JWT

---

config/schedule.yml

la conf pour Sidekiq-cron était manquante pour staging

Fix sidekiq-cron conf for staging

---

Gemfile
Gemfile.lock
app/lib/access_token.rb
spec/spec_helper.rb

Cette PR est courte mais il y a pas mal de choses à dire ; mes commentaires sont plus bas

Code coverage

---

app/concepts/user/operation/create.rb
spec/concepts/user/operation/create_spec.rb

This is for Signup integration.

Don't downcase email on save

---

app/concepts/user/contract/ask_password_renewal.rb
app/concepts/user/contract/confirm.rb
app/concepts/user/contract/password_params.rb
app/concepts/user/contract/reset_password.rb
app/concepts/user/operation/ask_password_renewal.rb
app/concepts/user/operation/reset_password.rb
app/controllers/users_controller.rb
app/mailers/jwt_api_entreprise_mailer.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/renew_account_password.html.erb
app/views/user_mailer/renew_account_password.text.erb
config/application.rb
config/dry_validation_errors.yml
config/environments/development.rb
config/environments/test.rb
config/routes.rb
db/migrate/20191205143354_add_pwd_renewal_token_to_user.rb
db/migrate/20191210155546_add_pwd_renewal_token_sent_at_to_user.rb
db/schema.rb
lib/tasks/db_seed/roles.rake
spec/concepts/user/operation/ask_password_renewal_spec.rb
spec/concepts/user/operation/confirm_spec.rb
spec/concepts/user/operation/reset_password_spec.rb
spec/controllers/users_controller_spec.rb
spec/mailers/jwt_api_entreprise_mailer_spec.rb
spec/mailers/user_spec.rb
spec/models/user_spec.rb
spec/support/shared_example.rb

* reset d'un mot de passe en deux parties : l'usager fournit une adresse email et on envoie un lien de régénération de mot de passe, puis l'usager fournit un nouveau mot de passe via ce lien.
* fix #32 
Concernant les tests Travis qui ne passent pas, si quelqu'un à une idée je suis curieux. On dirait que Timecop ne marche pas dans la CI.
Il y a des trucs dont je suis pas trop satisfait dans les tests de contrôleurs, je voudrai stub les opérations dans mes tests mais c'est compliqué vu que `params` est un ActionController::Parameters. J'ai l'intention de faire une passe de refactor dessus bientôt.

Reset password

---

app/concepts/jwt_api_entreprise/contract/update.rb
app/concepts/jwt_api_entreprise/operation/notify_expiration.rb
app/concepts/jwt_api_entreprise/operation/purge.rb
app/concepts/jwt_api_entreprise/operation/update.rb
app/controllers/jwt_api_entreprise_controller.rb
app/jobs/jwt_api_entreprise_purge_job.rb
app/models/jwt_api_entreprise.rb
config/routes.rb
config/schedule.yml
db/migrate/20191230093629_add_archived_to_jwt_api_entreprise.rb
db/schema.rb
spec/concepts/jwt_api_entreprise/operation/notify_expiration_spec.rb
spec/concepts/jwt_api_entreprise/operation/purge_spec.rb
spec/concepts/jwt_api_entreprise/operation/update_spec.rb
spec/controllers/jwt_api_entreprise_controller_spec.rb
spec/factories/jwt_api_entreprise.rb
spec/jobs/jwt_api_entreprise_purge_job_spec.rb
spec/models/jwt_api_entreprise_spec.rb
spec/models/user_spec.rb

* Action *update* pour archiver/blacklister un jeton 
* plus de notification d'expiration pour les JWT archivés ou blacklistés
* CRON job de suppression en base des jetons expirés
Commit par commit

Gestion des jetons 

---

app/concepts/user/operation/index.rb
app/controllers/users_controller.rb
spec/concepts/user/operation/index_spec.rb
spec/controllers/users_controller_spec.rb

Add filters to research users in the index

---

app/concepts/user/contract/create.rb
db/migrate/20200407150731_add_o_auth_api_gouv_id_to_users.rb
db/schema.rb
spec/concepts/user/operation/create_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/helpers/factories/users.rb
spec/models/user_spec.rb

The ID now has to be provided on user creation.

Add the OAuth API Gouv ID attribute to the user model

---

app/serializers/jwt_api_entreprise_index_serializer.rb
spec/controllers/jwt_api_entreprise_controller_spec.rb
spec/models/jwt_api_entreprise_spec.rb

field added: authorization_request_id

Add field in the Jwt return payload

---

app/views/jwt_api_entreprise_mailer/expiration_notice_old.html.erb
app/views/jwt_api_entreprise_mailer/expiration_notice_old.text.erb
spec/mailers/jwt_api_entreprise_mailer_spec.rb

Update link for JWT renewal process

---

app/concepts/role/operation/db_seed.rb
spec/concepts/role/operation/db_seed_spec.rb

Ajout des rôles INPI actes et bilans
https://3.basecamp.com/4318089/buckets/14906626/todos/3196470599
Lors de la mise en production : 
```ruby
bundle exec rake db_seed:roles RAILS_ENV=production
```

Add roles INPI x2

---

app/concepts/oauth_api_gouv/tasks/retrieve_user_info.rb
app/concepts/user/operation/transfer_ownership.rb
app/models/user.rb
db/migrate/20210210103428_add_tokens_newly_transfered_to_users.rb
db/schema.rb
spec/concepts/oauth_api_gouv/tasks/retrieve_user_info_spec.rb
spec/concepts/user/operation/create_spec.rb
spec/concepts/user/operation/transfer_ownership_spec.rb
spec/factories/users.rb
spec/models/user_spec.rb

Fin des notifications intempestives pour non transfert de compte 

---

app/concepts/user/contract/create.rb
app/concepts/user/contract/update.rb
db/migrate/20210324150631_change_users_oauth_api_gouv_id_to_string.rb
db/schema.rb
factories/users.rb
spec/concepts/oauth_api_gouv/tasks/retrieve_access_token_spec.rb
spec/concepts/oauth_api_gouv/tasks/retrieve_user_info_spec.rb
spec/concepts/user/operation/create_spec.rb
spec/concepts/user/operation/update_spec.rb
spec/controllers/users_controller_spec.rb
spec/fixtures/oauth_api_gouv_token.rb
spec/fixtures/vcr_cassettes/oauth_api_gouv_valid_call.yml
spec/mailers/user_spec.rb
spec/models/user_spec.rb

Changement du format de :oauth_api_gouv_id en String 

---

app/views/jwt_api_entreprise_mailer/satisfaction_survey.html.erb
app/views/jwt_api_entreprise_mailer/satisfaction_survey.text.erb
app/views/jwt_api_entreprise_mailer/satisfaction_survey/_embed_typeform.html
lib/mailer_previews/jwt_api_entreprise_mailer_preview.rb
spec/views/jwt_api_entreprise_mailer/satisfaction_survey.html.erb_spec.rb
spec/views/jwt_api_entreprise_mailer/satisfaction_survey.text.erb_spec.rb

Mise à jour de l'email d'enquête suite aux retours de @DorineLam

Enquête de satisfaction utilisateur (suite et fin) 

---

app/models/role.rb
spec/models/role_spec.rb

Cette PR propose :
* d'ajouter des tests sur le modèle `Role` ;
* de supprimer une relation inexistante.

Mise à jour de modèle

---

app/lib/mailjet/contact_properties_adapter.rb
app/models/user.rb
spec/lib/mailjet/contact_properties_adapter_spec.rb
spec/models/user_spec.rb

Ajout de nouvelles propriétés relatives aux rôles dans le payload à envoyer à [Mailjet](https://fr.mailjet.com/).
Il sera utile pour la suite, via une PR distincte, de traiter ce point : https://3.basecamp.com/4318089/buckets/21819387/todos/3819849077
Ceci pour rafraîchir la données, et possiblement corriger un éventuel bug dans une synchro précédente.

feat(Mailjet): add role properties

---

db/migrate/20210622155131_index_created_at_to_all_tables.rb
db/migrate/20210623074744_index_blacklisted_to_jwt_api_entreprises.rb
db/migrate/20210623075043_index_archived_to_jwt_api_entreprises.rb
db/migrate/20210623080558_index_exp_to_jwt_api_entreprises.rb
db/schema.rb
spec/models/contact_spec.rb
spec/models/incident_spec.rb
spec/models/jwt_api_entreprise_spec.rb
spec/models/role_spec.rb
spec/models/user_spec.rb

Cette PR ajoute quelques `index` sur des champs de recherche (c'est-à-dire ceux sur lesquels ont fait des `WHERE`).
J'en ai peut-être oublié, mais les principales colonnes sont là.

perf(db): add some missing indexes

---

app/controllers/api/private_metrics_controller.rb
spec/features/private_metrics_spec.rb

Previous refactor on namespacing breaks this controller.
Add a dummy test to avoid this.

FIX PrivateMetricsController

---

app/serializers/contact_serializer.rb
spec/controllers/api/users_controller_spec.rb

Closes
https://sentry.data.gouv.fr/organizations/sentry/issues/13668/?environment=production&project=15&referrer=alert_email

Bugfix Api::UsersController#show when a contact does not have a token

---

app/controllers/authenticated_users_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb
spec/features/user_details_spec.rb

* Vue avec les détails de l'utilisateur
* un before action pour limiter l'accès aux données du user connecté uniquement

Page détails utilisateur

---

app/controllers/users_controller.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/profile.html.erb
config/routes.rb
spec/features/transfer_account_spec.rb
spec/features/user_profile_spec.rb

Le bouton de transfer de compte utilisateur est maintenant fonctionnel

Transfer de compte utilisateur

---

app/models/contact.rb
app/models/jwt_api_entreprise.rb
spec/models/jwt_api_entreprise_spec.rb

Follow strong_migrations recommendations
https://github.com/ankane/strong_migrations#removing-a-column
Dans un 2e temps je flip it

Ignore old columns on some models before a removal

---

app/controllers/sessions_controller.rb
app/helpers/user_sessions_helper.rb
app/views/shared/_user_signed_in_side_menu.html.erb
config/routes.rb
spec/features/logout_spec.rb

Implement logout

---

Gemfile.lock

https://github.com/hotwired/turbo-rails/releases/tag/v0.8.2

Fix turbo-rails version

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/token_card.scss
app/views/jwt_api_entreprise/_jwt_api_entreprise.html.erb
app/views/jwt_api_entreprise/index.html.erb
app/views/jwt_api_entreprise/stats.html.erb
app/views/users/profile.html.erb
config/locales/fr.yml
spec/features/transfer_account_spec.rb

Passe sur les demandes de changements côté UX demandés par @DorineLam avant mise en prod du dashboard ([ici](https://3.basecamp.com/4318089/buckets/23847890/messages/4311977672) et [là](https://3.basecamp.com/4318089/buckets/23847890/messages/4333436617)).
Tout est fait sauf l'introduction d'un bouton/icône pour c/c le jeton.

Amélioration du CSS et du wording 

---

.github/workflows/ci.yml
README.md
bin/deploy

Related https://3.basecamp.com/4318089/buckets/14298426/messages/4356764372#__recording_4379875404

Enhance gitflow

---

app/views/jwt_api_entreprise/_jwt_api_entreprise.html.erb
config/locales/fr.yml
spec/features/token_details_spec.rb

Un autre edge case hop() 
https://sentry.data.gouv.fr/organizations/sentry/issues/14864/

Fix token details page when no expiration date

---

app/views/admin/tokens/index.html.erb
config/locales/fr.yml
spec/features/admin/token_index_spec.rb

Pour les admins, for research purposes.

Ajout de l'ID de demande DataPass dans la liste des jetons 

---

app/views/admin/private_metrics/index.html.erb

@hugolepetit C'est trop chouette de voir ces stats arriver sur le dashboard. Je me suis permise ces quelques propositions. Qu'en penses-tu ?

Proposition de reformulation de l'intro et ajout des accents

---

README.md
app/lib/seeds.rb
bin/deploy-sandbox
config/deploy.rb
db/seeds.rb
spec/lib/seeds_spec.rb

Ajout d'un script pour flush la db et reseed sur la sandbox frontale.

Enhance sandbox deployments

---

app/controllers/pages_controller.rb
app/views/pages/redoc.html.erb
config/api-entreprise-v3-openapi.yml
config/locales/fr.yml
config/routes.rb
public/api-entreprise-v3-openapi.yml
spec/features/pages_spec.rb

Path: /developers/redoc
Il y a 0 design de fait, vu que c'est embed ça reprend le DSFr
Des screenshots ci-dessous

Add simple redoc documentation

---

config/locales/fr.yml

Update wording for transfer

---

app/controllers/sessions_controller.rb
app/interactors/user/find_from_email.rb
app/interactors/user/notify_datapass_of_token_ownership.rb
app/interactors/user/update_oauth_api_gouv_id.rb
app/organizers/user/login.rb
app/organizers/user/sync_oauth_api_gouv_data.rb
spec/factories/users.rb
spec/features/signin_process_spec.rb
spec/organizers/user/login_spec.rb
spec/organizers/user/sync_oauth_api_gouv_data_spec.rb

Sync OAuth API Gouv ID and notify DataPass of new tokens owner

---

db/migrate/20220301154951_create_access_logs_view.rb
db/schema.rb

déployé en sandbox ; la vue est bien visible et utilisable

Add access_logs VIEW for Metabase usage

---

README.md
db/migrate/20220303181422_update_access_logs_view.rb
db/schema.rb
db/seed_access_logs.txt

cannot make any test without casting every time and all values have quotes around
ref : #350 
P.S: les tests en local sont très relou ; le modèle `AccessLog` est inutilisable car n'a pas de `created_at` etc... J'ai donc ajouté un script SQL pour ajouter une entrée en base et tester que la vue fonctionne bien cette fois-ci !

Update Access Log View config

---

app/assets/stylesheets/components/endpoint_card.scss

Assez fier d'avoir réussi celle là facilement ;D

Added spacing in endpoint cards views so labels stay in the bottom

---

app/models/endpoint.rb
app/views/endpoints/show.html.erb
config/locales/fr.yml
spec/features/endpoints/show_spec.rb
spec/fixtures/insee_unite_legale_example.json
spec/models/endpoint_spec.rb

Related to https://github.com/etalab/admin_api_entreprise/commit/a4277c2c04e6c33331a94bf6518b1bc84aafe722

Migrate tests to new serialization scheme

---

db/migrate/20220427143341_add_timestamp_with_paris_zone.rb
db/schema.rb

closes https://github.com/etalab/very_ansible/issues/80
cf https://github.com/etalab/very_ansible/pull/82

Add zone to access_logs_view timestamp

---

app/models/endpoint.rb
app/views/endpoints/show.html.erb
config/locales/fr.yml

Closes https://github.com/etalab/admin_api_entreprise/issues/421

Introduce endpoint#show Q&A

---

config/endpoints/10_dgfip_chiffres_affaires.yml
config/endpoints/13_dgfip_liasses_fiscales.yml
config/endpoints/14_dgfip_attestation_fiscale.yml
config/endpoints/15_urssaf_attestation_sociale.yml
config/endpoints/16_msa_conformites_cotisations.yml
config/endpoints/17_probtp_conformites_cotisations_retraite.yml
config/endpoints/18_fntp_cartes_pro_travaux_publics.yml
config/endpoints/19_cnetp_attestations_cotisations_conges_payes_chomage_intemperies.yml
config/endpoints/1_insee_unites_legales.yml
config/endpoints/22_qualibat_certifications_batiment.yml
config/endpoints/3_insee_adresse_etablissement.yml
config/endpoints/3_insee_etablissements.yml
config/endpoints/3_insee_siege_social.yml
config/endpoints/7_cmafrance_rnm.yml
config/endpoints/9_douanes_eori.yml

Relecture la partie Questions et réponses des fiches métiers

428 relecture des faq des nouvelles fiches métiers

---

spec/models/contact_spec.rb
spec/models/jwt_api_entreprise_spec.rb
spec/models/role_spec.rb
spec/models/user_spec.rb

Closes https://github.com/etalab/admin_api_entreprise/issues/425

Clean model tests

---

app/views/endpoints/show.html.erb
config/locales/fr.yml

- Retire les `&nbsp;`
- Modifie les H3 et H6

Retire nbsp titres fiche metier

---

app/views/endpoints/show.html.erb
config/endpoints/1_insee_unites_legales.yml
config/endpoints/3_insee_adresse_etablissement.yml
config/endpoints/3_insee_etablissements.yml
config/endpoints/3_insee_siege_social.yml

Ajouter les liens internes qui renvoient vers les autres fiches métiers.

441 ajouter liens internes dans les fiches métier

---

app/views/endpoints/_property.html.erb

Fix bug graphique où la bordure passe par dessus le texte

Ajoute un padding à la liste des attributs

---

app/views/attestations/index.html.erb
config/locales/fr.yml

@Samuelfaure proposition de PR pour avertir l'utilisateur sur ses engagements.
J'en ai profité pour changer la classe du titre H5, car pour moi c'est pas vraiment un titre mais plutôt un texte d'intro :)

457 UI attestations rappel cadre juridique

---

db/migrate/20220503093112_create_access_log_views.rb

je sais pas comment c'est passé sans que je le vois...
cf https://github.com/etalab/admin_api_entreprise/pull/426

SCUMBAG fix missing drop view

---

docs/tech-algolia.md
spec/spec_helper.rb

Reverts etalab/admin_api_entreprise#474
Erreur de push de mon coté

Revert "Tests/fix failing"

---

Gemfile.lock

@skelz0r c'est du boyscout / je peux merge direct ça aussi?

updating Gemfile.lock to remove annoying warnings

---

config/endpoints/10_dgfip_chiffres_affaires.yml
config/endpoints/13_dgfip_liasses_fiscales.yml
config/endpoints/14_dgfip_attestation_fiscale.yml
config/endpoints/15_urssaf_attestation_vigilance.yml
config/endpoints/16_msa_conformites_cotisations.yml
config/endpoints/17_probtp_conformites_cotisations_retraite.yml
config/endpoints/18_fntp_cartes_pro_travaux_publics.yml
config/endpoints/19_cnetp_attestations_cotisations_conges_payes_chomage_intemperies.yml
config/endpoints/1_insee_unites_legales.yml
config/endpoints/22_qualibat_certifications_batiment.yml
config/endpoints/24_inpi_brevets.yml
config/endpoints/25_inpi_marques.yml
config/endpoints/26_inpi_modeles.yml
config/endpoints/2_infogreffe_mandataires_sociaux.yml
config/endpoints/3_insee_adresse_etablissement.yml
config/endpoints/3_insee_etablissements.yml
config/endpoints/3_insee_siege_social.yml
config/endpoints/4_ministere_interieur_documents_associations.yml
config/endpoints/4_ministere_interieur_rna.yml
config/endpoints/5_inpi_actes.yml
config/endpoints/6_fabnum_conventions_collectives.yml
config/endpoints/7_cmafrance_rnm.yml
config/endpoints/9_douanes_eori.yml

@DorineLam j'ai retravaillé le format des YAML pour que ça soit plus facile à maintenir. Maintenant si tu c/c et que tu mets ça sur gist ça aura la même tête: du coup tu peux faire un gist, affiner et c/c directement ça marchera.

Clean endpoints YAML to be more maintenable

---

config/endpoints/21_ademe_certifications_rge.yml
config/endpoints/2_infogreffe_extrait_rcs.yml

En vue des deux endpoints qui arrivent.

440 ajoute fiches métier api extrait rcs et ademe rge

---

config/endpoints/16_msa_conformites_cotisations.yml
config/endpoints/1_insee_etablissements.yml
config/endpoints/21_ademe_certifications_rge.yml
config/endpoints/3_insee_adresse_etablissement.yml
config/endpoints/3_insee_siege_social.yml
config/endpoints/3_insee_unites_legales.yml
config/endpoints/5_inpi_actes.yml

Change l'ordre des tag - API Actes inpi

Harmonise les tags "Associations" ou "Entreprises" pour toutes les cartes du catalogue

---

.github/workflows/lint.yml
.github/workflows/security.yml
.github/workflows/tests.yml

J'ai mis le nez dans la CI et j'ai trouvé quelques simplifications : 
- utilisations de l'option `bundler-cache`
- simplification du setup Postgres
On peut me rappeler à quoi sert la variable d'env "CI" (COVERAGE c'est pour simple-cov de mémoire)
j'imagine qu'on peut faire pareil sur siade (later!)

Simplify CI files

---

config/endpoints/1_insee_etablissements.yml
config/endpoints/3_insee_siege_social.yml
config/endpoints/3_insee_unites_legales.yml

cf https://support.etalab.gouv.fr/#ticket/zoom/43740

doc: auto-entrepreneur fermé jamais disponible

---

Gemfile.lock

https://cert.ssi.gouv.fr/avis/CERTFR-2022-AVI-540/

Security fix - rails sanitizer

---

lib/tasks/token.rake

Update iat for token copy

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/code.scss
app/assets/stylesheets/components/markdown_to_html.scss
app/assets/stylesheets/dsfr-extensions.scss
app/assets/stylesheets/pages/documentation.scss
app/views/documentation/_banner.html.erb
app/views/documentation/_menu.html.erb
config/locales/documentation_entries.fr.yml
config/locales/fr.yml

Fait avec Dorine, juste du design, je merge

Boyscout: design changes

---

app/assets/javascripts/controllers/algolia_search_catalogue_controller.js
app/assets/stylesheets/pages/catalogue.scss
app/assets/stylesheets/shame.scss
app/controllers/endpoints_controller.rb
app/models/endpoint.rb
app/views/endpoints/_endpoint.html.erb
app/views/endpoints/index.html.erb
config/endpoints/15_urssaf_attestation_vigilance.yml
config/endpoints/template.yml.example
config/locales/fr.yml

Pour le moment ça ne cherche que sur le titre, description et fournisseur de données.
On pourra affiner ofc.

Implement basic search on catalogue

---

config/endpoints/14_dgfip_attestation_fiscale.yml

@Haelle voici ma proposition de transformation de la doc. Je suis pour retirer la référence au BNC BIC et BA qui n'a pas été confirmée.

Maj du contenu attestation fiscale

---

config/environments/development.rb
config/environments/test.rb

URL en français sur dashboard

---

app/assets/stylesheets/pages/home.scss
app/views/pages/home.html.erb
app/views/pages/home/_section_newsletter.html.erb
config/locales/fr.yml

Je tag pour review pour info, mais @DorineLam  le veut deploy aujourd'hui + c'est presque du boyscout donc je me permettrais de merger d'ici une heure

Added homepage section Newsletter

---

Gemfile

Move listen in production group

---

app/models/documentation_entry.rb
app/views/documentation/_menu.html.erb
config/locales/documentation_entries.fr.yml

C'est quasiment du boyscout et j'en aurais besoin pour une autre PR pour le rebase de la mort donc je vais merge direct

Site v3/fixed anchors

---

app/assets/javascripts/controllers/algolia_search_catalogue_controller.js

Reverts etalab/admin_api_entreprise#576

Revert "fix algolia search on catalogue"

---

config/locales/fr.yml

Correction du mot status (anglais) en statut (fr)

Update fr.yml (Correction orthographe status)

---

app/models/endpoint.rb
app/views/endpoints/show.html.erb
config/endpoints/13_dgfip_liasses_fiscales.yml

Tu peux itérer sur le wording @DorineLam ici https://github.com/etalab/admin_api_entreprise/commit/166f503d4b729fed6ef86ae014bf721342c96403 
Ça me parait important de l'écrire vu que ça va bouger (soon).

Ajout d'un disclaimer pour les liasses fiscales

---

config/locales/faq_entries.fr.yml

Ajoute une question réponse qui nous permet de donner l'URL du bureau ouvert et les détails

Ajoute Q&R sur le bureau ouvert

---

app/views/endpoints/show.html.erb

https://3.basecamp.com/4318089/buckets/24680202/todos/5102410607

Fiche métier - Déplace le bloc erreurs sous le bloc données

---

app/controllers/api/datapass_webhooks_controller.rb
app/interactors/datapass_webhook/create_token.rb
app/models/token.rb
app/organizers/datapass_webhook.rb
app/organizers/datapass_webhook/api_entreprise.rb
app/organizers/datapass_webhook/api_particulier.rb
config/routes.rb
spec/controllers/api/datapass_webhooks_controller_spec.rb
spec/factories/datapass_webhooks.rb
spec/factories/tokens.rb
spec/models/token_spec.rb
spec/organizers/datapass_webhook/api_entreprise_spec.rb
spec/organizers/datapass_webhook/api_particulier_spec.rb

Related to https://github.com/betagouv/datapass/pull/626

Handles API Particulier webhooks

---

config/locales/documentation_entries.fr.yml

Complète infos de la table de correspondance

Précise les évolutions entre V2 et V3 suite retours utilisateurs

---

config/deploy.rb

Corrections identiques à celles faites [sur siade](https://github.com/etalab/siade/pull/194/files).

deploy.rb : correction de permission et mises en variables

---

app/views/transfer_user_account/_new.html.erb
app/views/user_mailer/transfer_ownership.html.erb
app/views/user_mailer/transfer_ownership.text.erb
config/locales/faq_entries.fr.yml
config/locales/fr.yml

Cette PR propose de rendre plus explicites les responsabilités auxquelles le nouveau destinataire du compte s'engage.
Bilan du parcours actuel lisible ici => https://3.basecamp.com/4318089/buckets/26509199/messages/5091475018
La PR modifie plusieurs composants : 
- La popup de transfert de compte
- La notification indiquant que le compte a été transféré
- Les emails envoyés au destinataire
- La partie de la FAQ qui est dédié à ça

Modifie transfert de compte

---

app/controllers/token_controller.rb
app/views/token/_token.html.erb
app/views/token/renew.html.erb
config/brakeman.ignore
config/locales/fr.yml
config/routes.rb
docs/tech-modal-turbo.md
spec/features/token_details_spec.rb
spec/features/token_renew_spec.rb
spec/features/user_tokens_spec.rb

fix #633 
Il reste juste à @DorineLam à remplir le texte :)

Added turbo modal before renewing link

---

app/views/api_entreprise/tokens/renew.html.erb
config/locales/api_entreprise/fr.yml

Suite à cette merge request https://github.com/etalab/admin_api_entreprise/issues/633
J'ajoute le contenu.
@Samuelfaure peux-tu vérifier que : 
- le lien fonctionne bien vers la FAQ ?
- le style bold fonctionne ?
- les retours à la ligne aussi ?

Modifie contenu popup renouveler jeton

---

app/assets/stylesheets/dsfr-extensions.scss
app/views/api_entreprise/pages/home.html.erb
app/views/api_entreprise/pages/newsletter.html.erb
app/views/api_entreprise/pages/newsletter/_banner.html.erb
app/views/api_entreprise/pages/newsletter/_main.html.erb
config/locales/api_entreprise/fr.yml

Demande: https://3.basecamp.com/4318089/buckets/24680202/todos/5297581443#__recording_5302594671
Home:
Infolettre:

Added banner on infolettre page

---

app/views/api_entreprise/cas_usages/_list-api.html.erb

fixed display bug on data opening

---

config/locales/api_entreprise/documentation_entries.fr.yml

Petit bug contenu des documentations

---

Gemfile
Gemfile.lock
spec/factories/tokens.rb
spec/factories/users.rb

Franchement cette gem a rarement un intérêt en pratique je trouve

Removed gem Faker

---

app/lib/seeds.rb
app/models/authorization_request.rb
app/models/token.rb
db/migrate/20220914094327_add_constraint_on_api_field_on_authorization_requests.rb
db/schema.rb
spec/factories/authorization_requests.rb
spec/interactors/datapass_webhook/find_or_create_authorization_request_spec.rb

PR à la suite de https://github.com/etalab/admin_api_entreprise/pull/685
Le clean est almost done (j'attends des confirmations pour flip des demandes), dès que c'est prêt ça pourra être merge/deploy ici.

AuthorizationRequest#api is required

---

app/services/open_bureau_date.rb
spec/services/open_bureau_date_spec.rb

now changing open bureau date with time

---

app/models/endpoint.rb
config/locales/api_entreprise/missing_endpoints.fr.yml

INPI: Actes are not ready yet

---

config/locales/api_entreprise/documentation_entries.fr.yml

@Charlottecho suite à ton retour, voici ce qui peut être ajouté dans le guide de migration :

Ajoute phrase jeton d'accès identique

---

config/locales/api_entreprise/documentation_entries.fr.yml

Cette PR : 
- Précise la doc du paramètre d'appel 'reciptient'
- ajoute une doc sur l'environnement de staging

Ajout contenu doc tech

---

config/api-entreprise-v3-openapi.yml
config/endpoints/1_insee_etablissements.yml
config/endpoints/3_insee_unites_legales.yml
config/locales/api_entreprise/cas_usages_entries.fr.yml
spec/fixtures/insee_unite_legale_example.json

Suite à la nouvelle clé ajoutée (ESS), cette PR précise les cas d'usages.

Cas usages précision ESS

---

config/endpoints/2_infogreffe_extrait_rcs.yml
config/endpoints/2_infogreffe_mandataires_sociaux.yml

Cette PR propose d'ajouter une Q&R dans :
- L'api mandataires sociaux
- L'api extrait rcs
pour expliquer la différence entre les deux données

Fiche métier Q&R - Différence mandataires sociaux

---

config/api-entreprise-v3-openapi.yml
spec/fixtures/insee_unite_legale_example.json

Boyscout update openapi

---

bin/deploy-sandbox
bin/deploy-staging

Otherwise it'll deploy 2 times on the same host

Remove domain for deploy task

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Ajoute cette précision dans les fiches cas d'usage

Précise que la tranche effectif de l'API Insee concerne l'année N-2/-3

---

config/locales/api_entreprise/fr.yml

Suite retours utilisateurs, modifie le texte de la section concernant l'abonnement aux notifications incidents :

Modifie la formulation

---

app/views/api_entreprise/tokens/_user_tokens_list.html.erb
app/views/shared/_token_share_warning.html.erb
app/views/shared/public_token_magic_links/_show.html.erb
config/locales/fr.yml

fix https://github.com/etalab/admin_api_entreprise/issues/789

Added encart with warning about token sharing

---

config/initializers/sidekiq.rb

File.exists? seems to no longer .. exists (lol)

Harden sidekiq production loading for ruby 3.2.x

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Oubli de la branche https://github.com/etalab/admin_api_entreprise/pull/832

Exemples pour Cas usage MP

---

config/endpoints/13_dgfip_liasses_fiscales.yml

fix https://github.com/etalab/admin_api_entreprise/issues/792
Avant de merger faut que je fasse un point sur l'API, me semble qu'il restait un dico excel à implémenter

Removed banneer liasse fiscale

---

lib/tasks/token.rake
spec/lib/tasks/token_spec.rb

This reverts commit b240f6aa7eabc7d1d36afee568757950fb2c0cba.

Revert "Remove blakclist task"

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Suite validation par la commune, nous pouvons afficher le témoignage

Affiche citation ville de Vénissieux

---

app/views/api_entreprise/endpoints/show.html.erb
config/locales/api_entreprise/fr.yml

Closes https://github.com/etalab/admin_api_entreprise/issues/899

Endpoint#show for collection: enhance view

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/views/api_entreprise/endpoints/_property.html.erb

Closes https://github.com/etalab/admin_api_entreprise/issues/905

Endpoint#show: renders link in attribute's description clickable

---

Gemfile.lock

fixing issue https://github.com/mikel/mail/issues/1541

Update mail gem

---

config/deploy.rb
config/initializers/frontal.rb
config/initializers/frontal_mailer.rb

Related https://github.com/etalab/very_ansible/issues/341

Use env var setup by ansible to specify frontal and sends emails

---

app/controllers/api_entreprise/attestations_controller.rb
app/controllers/api_entreprise/tokens_controller.rb
app/controllers/api_particulier/users_controller.rb
app/interactors/datapass_webhook/create_token.rb
app/models/authorization_request.rb
app/models/contact.rb
app/models/token.rb
app/services/tokens_associated_to_email_query.rb
spec/factories/authorization_requests.rb
spec/factories/tokens.rb
spec/features/api_entreprise/attestations_spec.rb
spec/interactors/datapass_webhook/archive_previous_token_spec.rb
spec/models/authorization_request_spec.rb
spec/models/contact_spec.rb
spec/models/token_spec.rb
spec/organizers/datapass_webhook/api_entreprise_spec.rb
spec/services/tokens_associated_to_email_query_spec.rb

closes https://github.com/etalab/admin_api_entreprise/issues/892

Defining priority on valid token

---

app/interactors/magic_link/validate_user_from_access_token.rb
spec/support/shared_examples/signin_process_magic_link.rb

fix https://github.com/etalab/admin_api_entreprise/issues/933

fixed bug when trying to login with wrong access_token

---

app/controllers/api_entreprise/authorization_requests_controller.rb
app/models/authorization_request.rb
spec/features/api_entreprise/user_profile_spec.rb
spec/models/authorization_request_spec.rb

closes https://github.com/etalab/admin_api_entreprise/issues/721
Petite question concernant cette PR. J'ai pas fais de tests parce que je sais pas où le faire.
La logique me dit que c'est un test de controller, mais j'ai l'impression que vous faites plutot des tests de feature. C'est quoi la règle pour décider ?

[Bug] Fixes display of authorization request

---

.gitignore

add todo file to gitignore

---

app/lib/algolia_reindexer.rb
lib/tasks/algolia.rake
spec/lib/algolia_reindexer_spec.rb

Closes https://github.com/etalab/admin_api_entreprise/issues/978

algolia task catches algolia error and print errors

---

app/views/api_entreprise/pages/newsletter/_main.html.erb
config/locales/api_entreprise/fr.yml

Le widget actuel d'inscription à la newsletter en page d'accueil va être supprimé par Mailjet, il faut le remplacer.

[Page accueil] Ajout nouveau widget : inscription newsletter

---

app/views/api_entreprise/endpoints/_endpoint.html.erb
app/views/api_entreprise/endpoints/index.html.erb
spec/features/api_entreprise/endpoints/index_spec.rb

No automated tests, no glory 🤷

API Entreprise catalogue: harden algolia search

---

app/controllers/concerns/public_token_magic_links_management.rb
app/views/shared/sessions/_new.html.erb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml
config/locales/fr.yml
spec/features/api_entreprise/access_spec.rb

Note: Merge sur la branche login/full_moncomptepro

Login/full moncomptepro: Suppression login magic link + test feature

---

.rubocop.yml

Pour supprimer le warning, mostly

add rubocop extension

---

config/endpoints/api_entreprise/17_probtp_conformites_cotisations_retraite.yml

Suite retour Probtp, précision de la doc.

[Fiche métier] Api probtp doc

---

spec/features/api_entreprise/endpoints/index_spec.rb

fix https://github.com/etalab/admin_api_entreprise/issues/1037

retry flaky test more

---

app/views/api_entreprise/tokens/index.html.erb
config/locales/api_entreprise/fr.yml
spec/features/api_entreprise/user_tokens_spec.rb

fix https://github.com/etalab/admin_api_entreprise/issues/1051

Displaying message when no tokens on token index

---

.rubocop.yml
db/migrate/20230529094940_delete_admin_from_users.rb
db/schema.rb

fix https://github.com/etalab/admin_api_entreprise/issues/1053

removed column Admin from users

---

config/api-entreprise-v3-openapi.yml
config/api-particulier-openapi.yml
spec/fixtures/insee_unite_legale_example.json

Fix de spec/services/open_api_schema_to_example_spec.rb
Et retry sur un test flaky

fix faulty test

---

config/endpoints/api_particulier/education_nationale_statut_eleve.yml

Ajoute documentation sur le statut boursier suite retours du FD

[API PArticulier] Statut boursier api scolarité : précision fiabilité

---

app/services/redis_service.rb
app/services/status_page.rb
config/application.rb
config/cache_redis.yml
config/deploy.rb
config/environments/development.rb
config/environments/production.rb
config/environments/sandbox.rb
config/environments/staging.rb
config/environments/test.rb
config/initializers/sidekiq.rb
config/redis.yml
spec/services/status_page_spec.rb

Related https://github.com/etalab/admin_api_entreprise/issues/1078
Closes https://github.com/etalab/admin_api_entreprise/issues/825

Refactor redis config 

---

app/controllers/concerns/sessions_management.rb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml

Closes https://github.com/etalab/admin_api_entreprise/issues/1085

Unknown user: enhance error message on failed signed in

---

Gemfile
Gemfile.lock
app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/models/user_authorization_request_role.rb
config/initializers/strong_migrations.rb
db/migrate/20230621113853_add_indexes_to_user_authorization_request_roles.rb
db/schema.rb
spec/models/user_authorization_request_role_spec.rb
spec/organizers/datapass_webhook/api_entreprise_spec.rb

Previous version tries to create a model with an invalid user (which causes a PG error)
Closes https://errors.data.gouv.fr/organizations/sentry/issues/2783/

DatapassWebhook: harden when there is invalid contacts

---

app/services/api_entreprise/open_api_definition.rb
config/endpoints/api_entreprise/31_qualifelec_certificat.yml

Added the qualifelec documentation

---

app/views/shared/_alerts.html.erb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml

Ref https://mattermost.incubateur.net/betagouv/pl/xecifuwwajd6jra5o5y91ffdcw

Enhance not found message for MonComptePro connexion

---

app/controllers/api_entreprise/restricted_token_magic_links_controller.rb
app/controllers/api_particulier/restricted_token_magic_links_controller.rb
app/controllers/concerns/restricted_token_magic_links_management.rb
app/views/api_particulier/tokens/_token.html.erb
app/views/api_particulier/users/profile.html.erb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/faq_entries.fr.yml
config/locales/api_particulier/fr.yml
config/locales/fr.yml
config/routes/api_particulier.rb
spec/features/api_entreprise/create_token_magic_link_spec.rb
spec/features/api_particulier/create_token_magic_link_spec.rb

API Particulier: can share tokens through magic links

---

app/assets/stylesheets/api_entreprise/pages/home/_section_partners.scss
app/helpers/algolia_query_helper.rb
app/views/api_entreprise/pages/home/_section_partners.html.erb
spec/features/api_entreprise/homepage_spec.rb
spec/spec_helper.rb

@DorineLam Ça m'énerve que cette section soit pas centré en responsive donc je fais cette micro-PR, qu'en penses-tu?
AVANT
APRES
Je préfère le 2, WDYT?

Enhancements homepage / algolia

---

Makefile
README.md
config/database.yml
docker-compose.yml

fix #989 
Je voulais faire les tests aussi mais flemme, faut rajouter tout un container avec Chrome pour Capybara et reconfig redis...

using a makefile to simply docker

---

config/endpoints/api_particulier/cnaf_quotient_familial.yml

Thread Mattermost de la discussion : https://mattermost.incubateur.net/betagouv/pl/6nkktbk9hirodx7g9xtq6shyjh

API-700 [API Part - QF V1] Changement de définition du QF

---

app/controllers/api_entreprise/pages_controller.rb
app/controllers/api_particulier/pages_controller.rb
app/views/layouts/api_entreprise/application.html.erb
app/views/layouts/api_entreprise/no_newsletter_banner.html.erb
app/views/layouts/api_particulier/application.html.erb
app/views/layouts/api_particulier/no_newsletter_banner.html.erb

fix https://github.com/etalab/admin_api_entreprise/issues/1174

factorized layout

---

app/jobs/concerns/mailjet_helpers.rb
app/jobs/schedule_authorization_request_mailjet_email_job.rb
app/jobs/schedule_expiration_notice_mailjet_email_job.rb

Ref https://github.com/etalab/admin_api_entreprise/issues/1088

Mailjet error 400: track authorization request id

---

config/api-entreprise-v3-openapi.yml
config/api-particulier-openapi.yml
config/endpoints/api_particulier/pole_emploi.yml

Pour run sous docker:
```sh
docker-compose up --build -e LOAD_LOCAL_OPEN_API_DEFINITIONS=true
```
Related https://github.com/etalab/siade/pull/861

API Particulier: Pole Emploi indemnites

---

app/assets/javascripts/controllers/algolia_search_catalogue_controller.js

No longer dummy show/hide
Closes https://github.com/etalab/admin_api_entreprise/issues/1154

Displays catalogue results in relevancy order

---

app/interactors/datapass_webhook/find_or_create_authorization_request.rb
app/interactors/datapass_webhook/find_or_create_user.rb
app/lib/seeds.rb
app/models/user.rb
app/views/api_entreprise/contacts/_contact.html.erb
app/views/api_entreprise/users/_user.html.erb
config/locales/api_entreprise/fr.yml
spec/factories/datapass_webhooks.rb
spec/factories/users.rb
spec/features/api_entreprise/token_contacts_spec.rb
spec/interactors/datapass_webhook/find_or_create_user_spec.rb

Closes https://linear.app/pole-api/issue/API-986/supprimer-le-phone-number-sur-le-site

Remove phone number on users

---

db/migrate/20221025080557_initial_schema.rb

Make migration strong migration compliant

---

app/interactors/datapass_webhook/archive_current_token.rb
app/interactors/datapass_webhook/revoke_current_token.rb
app/models/authorization_request.rb
app/organizers/datapass_webhook/api_entreprise.rb
app/organizers/datapass_webhook/api_particulier.rb
spec/interactors/datapass_webhook/archive_current_token_spec.rb
spec/interactors/datapass_webhook/revoke_current_token_spec.rb

J'ai split en 2 Commit.
IMO c'est good, la question est, est ce qu'il y a d'autres impact que cela à ces évènements. Pas d'après ce qui a été listé dans linear.

Archive/Revoque Datapass Event

---

config/endpoints/api_entreprise/24_qualifelec_certificat.yml
config/endpoints/api_entreprise/5_inpi_rne_beneficiaires.yml
config/locales/api_entreprise/cas_usages_entries.fr.yml

Api 878 Nouvelles donnees dans les cas d'usages

---

config/endpoints/api_particulier/cnaf_msa_complementaire_sante_solidaire.yml
config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/endpoints/api_particulier/cnous_student_scholarship.yml
config/endpoints/api_particulier/education_nationale_statut_eleve.yml
config/endpoints/api_particulier/mesri_student_status.yml

UI Paramètres d'appel obligatoires

---

.github/workflows/tests.yml

fix https://github.com/etalab/admin_api_entreprise/issues/1172
(du moins on tente)

Add new action to register gpg key to sign commits

---

config/endpoints/api_particulier/cnaf_quotient_familial.yml

Ajout de la date de fin de mise en production de cette API et URL vers la doc de la v2

Ajout date fin de l'API CNAF

---

app/models/api_particulier/endpoint.rb
app/views/api_particulier/endpoints/_details.html.erb
config/locales/api_particulier/fr.yml

This reverts commit e90151c1dcef6cd2cbaa129072d751c747987fc1.
Closes https://linear.app/pole-api/issue/API-975/re-ajouter-les-heures-de-maintenances-sur-les-fiches#comment-2c19b65f

Revert "Retire le bloc de maintenance"

---

config/initializers/sentry.rb

Related https://errors.data.gouv.fr/organizations/sentry/issues/4674/ and https://errors.data.gouv.fr/organizations/sentry/issues/4675/

Do not activate Sentry if not frontale

---

config/endpoints/api_entreprise/5_inpi_rne_beneficiaires.yml

Ajout des informations relatives à l'accès aux données complètes et un lien vers la doc de l'INPI

FAQ RBE: add link to INPI full data

---

app/models/token.rb

C'est dommage que j'en ai pas profité pour supprimer l'autre champs de la db. On fera ca une prochaine fois.

Token: removed ignored archived and blacklisted

---

app/controllers/api_entreprise/authorization_requests_controller.rb
app/controllers/api_particulier/authorization_requests_controller.rb
app/controllers/concerns/authorization_requests_management.rb
app/helpers/authorization_request_helper.rb
app/models/authorization_request.rb
app/services/token_export.rb
app/views/shared/authorization_requests/show.html.erb
config/locales/api_entreprise/fr.yml
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
spec/features/api_particulier/authorization_request_spec.rb
spec/models/authorization_request_spec.rb
spec/services/token_export_spec.rb

2 Jour qu'il n'y a pas eu de merge sur master à cause des flaky tests et on a besoin de deploy

Forcing merge into master because flaky test

---

app/helpers/new_token_helper.rb
app/views/api_particulier/users/profile.html.erb
config/locales/api_particulier/fr.yml

En se connectant sur api-part, 
Pour voir le boutton il faut qu'il y ai un fichier dans le dossier `root/token_export`
Si vous êtes connecté avec le user `user@yopmail.com` le fichier doit s'appeler `demarche_user@yopmail.com.csv`
Afin que le fichier soit téléchargeable il ne doit pas être vide.

Added button to download new tokens for api part

---

app/views/shared/api_particulier/header/_menu.html.erb
config/locales/api_particulier/fr.yml

C'est le même lien que API Entreprise, pas le même motif mais on verra bien si ça pose vraiment problème
Je compte merge/deploy d'ici vendredi matin (demain matin) on va l'annoncer demain

API-1532 Ajout d'une bannière pour le bureau ouvert API Part

---

config/locales/api_entreprise/documentation.fr.yml
config/locales/api_entreprise/faq_entries.fr.yml
config/locales/api_particulier/documentation.fr.yml
config/locales/api_particulier/faq_entries.fr.yml

http://entreprise.api.localtest.me:3000/developpeurs?disable_search=1#surveillance-etat-fournisseurs

API Entreprise: Documentation routes de pings

---

spec/features/api_entreprise/token_contacts_spec.rb
spec/features/api_particulier/endpoints/index_spec.rb
spec/jobs/schedule_expiration_notice_mailjet_email_job_spec.rb

Ref https://linear.app/pole-api/issue/API-1235/ci-tests-flaky-sur-admin

Harden some flaky tests

---

app/services/attestations_scope_service.rb

fix https://linear.app/pole-api/issue/API-1085/problemes-telechargement-attestations-en-prod

fix new scopes on attestations

---

config/locales/api_particulier/faq_entries.fr.yml

Mise à jour de la liste des éditeurs

MAJ_liste_editeurs.yml

---

Gemfile
Gemfile.lock
app/controllers/concerns/public_token_magic_links_management.rb
app/models/magic_link.rb
app/models/token.rb
app/services/tokens_associated_to_email_query.rb
app/views/shared/public_token_magic_links/_show.html.erb
config/environments/development.rb
config/environments/test.rb
db/migrate/20231108173009_migrate_from_json_to_jsonb.rb
db/schema.rb
spec/features/api_entreprise/show_token_from_magic_link_spec.rb
spec/features/api_particulier/show_token_from_magic_link_spec.rb
spec/models/token_spec.rb
spec/services/tokens_associated_to_email_query_spec.rb

Have to clean some clunky associations in order to make bullet happy on N+1 queries and eager loading.

Install bullet (for N+1 queries/eager loading)

---

app/facade/entreprise_with_attestations_facade.rb
spec/facade/entreprise_with_attestations_facade_spec.rb

fix https://errors.data.gouv.fr/organizations/sentry/issues/130272/?alert_rule_id=7&alert_timestamp=1699448050667&alert_type=email&environment=production&project=9&referrer=alert_email

scumbag typo

---

app/controllers/concerns/authorization_requests_management.rb
app/models/token.rb
app/services/access_logs_counts.rb
app/views/shared/authorization_requests/show.html.erb
config/locales/api_entreprise/fr.yml
spec/features/api_particulier/authorization_request_spec.rb
spec/models/token_spec.rb

Ca commence à faire un joli fichier.
J'ai à la fois envie de faire un peu plus de partial et en même temps, aucun de ces composants n'est prévu d'être réutilisé (sauf ceux du token que j'ai déjà mis en partial).

AuthorizationRequest: show - Added old token informations

---

app/controllers/api_particulier/new_tokens_controller.rb
app/services/token_export.rb
spec/controllers/api_particulier/new_tokens_controller_spec.rb
spec/services/token_export_spec.rb

Le seul truc qui me gonfle avec cette PR, c'est le chemin du fichier en dur, 
Aussi j'ai peur qu'avec les changements de droits qu'à fait aurelien sur l'ouverture des fichiers tout casse parce que admin n'aurait pas les droit sur le fichier api :O
J'ai vérifié 4 fois la mep des emails => demarche mais je pense que ca vaut le coup d'oeil méticuleux : https://linear.app/pole-api/issue/API-1424/envoyer-lemail-aux-editeurs#comment-76e2f296

Reworked TokenExport mechanism

---

app/controllers/api_particulier/authenticated_users_controller.rb
app/controllers/api_particulier/new_tokens_controller.rb
app/services/token_export.rb
app/views/api_particulier/users/profile.html.erb
spec/controllers/api_particulier/new_tokens_controller_spec.rb
spec/features/api_particulier/new_tokens_file_spec.rb
spec/services/token_export_spec.rb

On utilise les emails de la db now, ca simplifie le code.
Tant mieux, rien n'est perdu parce que le code est quasiment iso.
Reste les données à mettre à jour.

Fix new tokens download

---

app/views/api_entreprise/faq/index.html.erb
app/views/api_particulier/faq/index.html.erb
app/views/shared/faq/_faq_entry.html.erb

Use same code for both apps, no need to make differences here

Bugfix API Particulier FAQ search

---

app/decorators/token_decorator.rb
spec/features/api_entreprise/token_contacts_spec.rb
spec/helpers/feature_helper.rb

Test don't flaky no more

---

app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
app/jobs/schedule_authorization_request_email_job.rb
spec/interactors/datapass_webhook/schedule_authorization_request_emails_spec.rb
spec/jobs/schedule_authorization_request_email_job_spec.rb

Old complexity leftover from Mailjet wasnt
properly cleaned

Fix interface bug between jobs

---

app/helpers/scope_helper.rb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml

Cette PR :
- Ajoute tous les scopes présents dans le fichier `siade/config/authorizations.yml`
- Uniformise les labels
- précise le fournisseur pour chaque API
- indique si l'API propose de la donnée open data
- indique si l'API est obsolete

Ajoute scopes et uniformise labels 

---

config/endpoints/api_entreprise/9_douanes_eori.yml

FYI @Charlottecho j'ai ajouté le lien vers le site où on peut tester l'API EORI en ligne et j'ai corrigé le lien cassé

Fix link and add another one

---

app/helpers/authorization_request_helper.rb
app/views/shared/authorization_requests/_breadcrumb.html.erb
app/views/shared/authorization_requests/_header.html.erb
app/views/shared/authorization_requests/index.html.erb
app/views/shared/authorization_requests/show.html.erb
app/views/shared/tokens/_detail_short.html.erb
app/views/shared/users/_user.html.erb
config/locales/api_entreprise/fr.yml
config/locales/fr.yml
spec/features/api_particulier/authorization_request_show_spec.rb
spec/features/api_particulier/show_token_spec.rb

- Ajuste bouton vers le compte
- Règle la grille du tableau des habilitations et ajuste la taille des typos et des marges pour plus de lisibilité
- Layout et fond blanc pour les espaces habilitations et compte

Ajustements UI compte utilisateur

---

app/views/api_entreprise/user_mailer/notify_datapass_for_data_reconciliation.html.mjml
app/views/api_entreprise/user_mailer/notify_datapass_for_data_reconciliation.text.erb
app/views/api_entreprise/user_mailer/transfer_ownership.html.mjml
app/views/api_entreprise/user_mailer/transfer_ownership.text.erb
config/locales/api_entreprise/faq_entries.fr.yml
config/locales/api_particulier/faq_entries.fr.yml
config/locales/fr.yml

Cette PR clos également : 
- https://linear.app/pole-api/issue/API-1762/mettre-a-jour-la-faq-api-particulier-et-api-entreprise
- https://linear.app/pole-api/issue/API-1765/mail-datapass-parler-dhabilitation

Transfert des habilitations : FAQ et e-mails

---

app/controllers/concerns/transfer_user_account_management.rb
app/views/shared/transfer_user_account/_new.html.erb
app/views/shared/users/_user.html.erb
config/locales/fr.yml
spec/features/api_entreprise/transfer_account_spec.rb
spec/features/api_particulier/transfer_account_spec.rb

API-1855 Précise en détail les process de transfert d'habilitation dans l'espace admin

---

app/models/token.rb

IMO faudrait dig plus sur pourquoi et corriger la db. 
Je me note ca, pour plus tard.

Fixing extra_info on token sometime being empty

---

app/controllers/api_entreprise/pages_controller.rb
app/controllers/api_particulier/pages_controller.rb
app/views/api_entreprise/pages/_cgu.html.erb
app/views/api_entreprise/pages/_donnees_personnelles.html.erb
app/views/api_entreprise/pages/donnees_personnelles.html.erb
app/views/api_particulier/pages/_donnees_personnelles.html.erb
app/views/api_particulier/pages/donnees_personnelles.html.erb
app/views/shared/api_entreprise/_footer.html.erb
app/views/shared/api_particulier/_footer.html.erb
app/views/shared/pages/mentions.html.erb
config/locales/api_entreprise/faq_entries.fr.yml
config/locales/api_particulier/faq_entries.fr.yml
config/routes/api_entreprise.rb
config/routes/api_particulier.rb
config/sitemap/api-entreprise.rb
spec/features/api_entreprise/pages_spec.rb
spec/features/api_particulier/pages_spec.rb

- FAQ prolongation du jeton
- FAQ Gestion des jetons quand on vient d'être habilité
- CGU API Entreprise
- Ajoute la page données personnelles pour API entreprise et API particulier

Amélioration doc API Part et API Entreprise

---

app/controllers/api_entreprise/errors_controller.rb
app/controllers/api_particulier/errors_controller.rb

Testé en sandbox
Avant :
Après: ça n'error plus, on obtient ça:
Good enough?

Layout "no container" error 500 with Gaffe

---

app/models/abstract_endpoint.rb
spec/models/api_entreprise/endpoint_spec.rb
spec/models/api_particulier/endpoint_spec.rb

Le test est un peu weak, l'alternative serait de faire un test de feature sur le bouton swagger pour tout les endpoints mais ça serait super overkill imo

fix capitalization errors in redoc tag

---

config/locales/api_particulier/cas_usages_entries.fr.yml

@DorineLam Ça te semble cohérent avec le métier?

added one cas d'usage for CSS

---

app/views/api_entreprise/endpoints/_details.html.erb
app/views/api_entreprise/endpoints/show.html.erb
app/views/api_particulier/endpoints/_details.html.erb
app/views/api_particulier/endpoints/show.html.erb
config/locales/api_entreprise/fr.yml
config/locales/api_particulier/fr.yml
spec/features/api_entreprise/endpoints/show_spec.rb
spec/features/api_particulier/endpoints/show_spec.rb

Moving button 'test cases' to details

---

config/endpoints/api_entreprise/13_dgfip_liasses_fiscales.yml

Doc imprimés liasses fiscales

---

.github/workflows/lint.yml
.github/workflows/security.yml
.github/workflows/tests.yml

v3 is deprecated
Same as https://github.com/etalab/siade/pull/1143

Update checkout action

---

app/views/shared/authorization_requests/index.html.erb

Removed usage of instance variable

BUGFIX - Impersonate user wasnot behaving properly

---

config/api-entreprise-v3-openapi.yml
config/api-particulier-openapi.yml
config/endpoints/api_particulier/cnaf_allocation_adulte_handicape.yml
config/endpoints/api_particulier/cnaf_allocation_soutien_familial.yml
config/endpoints/api_particulier/cnaf_msa_complementaire_sante_solidaire.yml
config/endpoints/api_particulier/cnaf_prime_activite.yml
config/endpoints/api_particulier/cnaf_revenu_solidarite_active.yml

[API-2377] doc fiches metier API Prestation

---

app/facade/entreprise_with_attestations_facade.rb
spec/facade/entreprise_with_attestations_facade_spec.rb

fix https://errors.data.gouv.fr/organizations/sentry/issues/138263/?alert_rule_id=7&alert_timestamp=1713339597783&alert_type=email&environment=production&project=9&referrer=alert_email

Fix error when whitespaces in SIREN

---

config/blog_posts/api_particulier/parametre-lieu-naissance-code-cog.md
config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/endpoints/api_particulier/cnaf_quotient_familial.yml
config/endpoints/api_particulier/cnav_allocation_adulte_handicape.yml
config/endpoints/api_particulier/cnav_allocation_soutien_familial.yml
config/endpoints/api_particulier/cnav_complementaire_sante_solidaire.yml
config/endpoints/api_particulier/cnav_prime_activite.yml
config/endpoints/api_particulier/cnav_revenu_solidarite_active.yml
config/locales/api_particulier/cas_usages_entries.fr.yml
config/locales/api_particulier/fr.yml
config/locales/api_particulier/providers.fr.yml

related https://github.com/etalab/siade/pull/1196

Renaming cnaf to cnav for relevant APIs

---

app/views/layouts/api_entreprise/application.html.erb
app/views/layouts/api_particulier/application.html.erb

à la demande de Arslane, on veut noindex staging/sandbox

Only indexing production for SEO

---

config/endpoints/api_entreprise/1_insee_successions.yml
config/endpoints/api_entreprise/24_qualifelec_certificat.yml
config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/locales/api_entreprise/cas_usages_entries.fr.yml

Ajoute mention pour les cas d'usage suivants : 
**Cas d'usage marchés publiques :** 
**Cas usages aides publiques / subventions asso / portail GRU instruction :** 
**Également taggé pour le cas d'usage détection de la fraude**

Cas d'usage Liens de successions

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml
config/endpoints/api_particulier/cnav_allocation_adulte_handicape.yml
config/endpoints/api_particulier/cnav_allocation_soutien_familial.yml
config/endpoints/api_particulier/cnav_complementaire_sante_solidaire.yml
config/endpoints/api_particulier/cnav_prime_activite.yml
config/endpoints/api_particulier/cnav_revenu_solidarite_active.yml

API CNAV : Message pour annonce pb d'appel avec nom d'usage

---

.gitignore
README.md
bin/deploy
bin/deploy-sandbox

Usage: ./bin/deploy [env] [branch]
You should have a valid access token defined in `.deploy_token` to use this script.
Check
https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event for more info

Rewrite deploy script

---

.github/workflows/tests.yml
bisect_run.sh

This is a temporary solution, be

Forcing specific seed in CI to prevent tests to fail

---

.rubocop.yml
Gemfile
Gemfile.lock
spec/controllers/api/datapass_webhooks_controller_spec.rb
spec/controllers/api/datapass_webhooks_v2_controller_spec.rb

added gem rubocop-rspec_rails as advised by rubocop also ran rubocop autocorrect
poke @Un3x

Maintenance rubocop

---

app/controllers/api/frontal_controller.rb
config/routes.rb
spec/controllers/api/frontal_controller_spec.rb

Will be used for frontal monitoring on status page

Introduce /api/frontal

---

config/locales/api_entreprise/faq_entries.fr.yml
config/locales/api_particulier/cas_usages_entries.fr.yml
config/locales/api_particulier/faq_entries.fr.yml

FAQ Modifie le paragraphe sur les données demandées

---

app/jobs/healthcheck_job.rb

Closes https://errors.data.gouv.fr/organizations/sentry/issues/142964/

HealthcheckJob: rescue temporary dns error

---

config/locales/api_entreprise/faq_entries.fr.yml

Remplacer "API Particulier "par "API Entreprise"

Correctif nom de l'API.yml

---

app/assets/stylesheets/api_entreprise/pages/home/_section_developers.scss
app/views/api_entreprise/pages/home/_section_developers.html.erb
config/initializers/cors.rb

Fix broken badge hyperping

---

config/endpoints/api_entreprise/5_inpi_rne_beneficiaires.yml

Dépendant de https://github.com/etalab/siade/pull/1322

API Entreprise: change RBE url

---

spec/rails_helper.rb
spec/spec_helper.rb

equalizing with https://github.com/etalab/siade/pull/1313/commits/66e346f446ff403a99619a8dd4d37a337abfbb8b

Moving coverage config to correct place

---

app/interactors/datapass_webhook/api_particulier/notify_reporters.rb
app/mailers/api_particulier/reporters_mailer.rb
app/views/api_particulier/reporters_mailer/approve.text.erb
app/views/api_particulier/reporters_mailer/submit.text.erb
spec/interactors/datapass_webhook/api_particulier/notify_reporters_spec.rb
spec/mailers/api_particulier/reporters_mailer_spec.rb

API Particulier: enhance reporter emails

---

app/views/admin/users/index.html.erb
app/views/api_entreprise/endpoints/show.html.erb
app/views/api_entreprise/pages/_cgu.html.erb
app/views/api_particulier/endpoints/show.html.erb
app/views/shared/authorization_requests/actions/_prolong.html.erb
app/views/shared/authorization_requests/show.html.erb
app/views/shared/tokens/prolong.html.erb

Detected with `erb-format`, prepare to massive lint here.

FIX missing HTML tags

---

.github/workflows/ci_cd.yml

This might have lead to weird errors in staging since it used the production environment configuration.
Also reduces the consumption of the CI.

Fixed staging deployment happening with prod deployment

---

config/endpoints/api_entreprise/5_inpi_rne_beneficiaires.yml

https://linear.app/pole-api/issue/API-3412/enlever-le-tag-beta-de-lapi-rbe#comment-1a565020

API-3412 Enlever le tag "beta" de l'API RBE

---

app/models/authorization_request.rb
spec/models/authorization_request_spec.rb

All validated authorization requests should be visible by users

Harden AuthorizationRequest#viewable_by_users

---

config/endpoints/api_entreprise/19_cnetp_attestations_cotisations_conges_payes_chomage_intemperies.yml
config/endpoints/api_entreprise/31_cibtp_attestations_cotisations_chomage_intemperies.yml

[API CIBTP et CNETP] Entreprises multisecteurs 

---

config/locales/api_particulier/faq_entries.fr.yml

Ajoute question spécifique formulaire transmission sécurisé

---

config/endpoints/api_particulier/mesri_student_status.yml

[APi Part - statut étudiant] Ajoute nombre d'étudiants inclus dans l'API

---

app/services/open_bureau_date.rb
spec/services/open_bureau_date_spec.rb

Could not find a more readable alternative that worked

Fix open bureau date

---

app/services/status_page.rb

J'ai mis both read et open timeout pour être sûr qu'on soit dépendants ni de l'un ni de l'autre (pas certain de là ou hyperping peut potentiellement ralentir)

increasing cache and limiting request time for status page

---

config/routes/api_particulier.rb

fix https://linear.app/pole-api/issue/API-3668/problemes-infra-espace-admin

Fix wrong route for api particulier status page

---

app/controllers/api_particulier/pages_controller.rb
app/services/abstract_open_api_definition.rb
app/services/api_particulier/open_api_definition.rb
app/views/shared/pages/redoc_v3.html.erb
bin/download_latest_open_api_definitions.sh
config/api-entreprise-v3-openapi.yml
config/api-particulier-openapi-v3.yml
config/api-particulier-openapi.yml
config/locales/fr.yml
config/routes/api_particulier.rb

Url is not accessible unless you type it in your browser for now. This is intended as we can share our url to specific people and continue our review.
This will also allow syntax checking on the siade_staging_data repository.
This commit can be reverted once the v3 will be the main swagger on the siade repository. This has been specified in the dedicated issue on linear.

Enable Access to API PART v3 swagger

---

config/initializers/cors.rb

protocol within config is not standard (does it work..?)

Enhance CORS config

---

config/endpoints/api_particulier/education_nationale_statut_eleve.yml

Ajout des élèves de maternelle dans la population concernée Mise à jour des informations sur la bascule d'année/année n+1

Mise à jour de la doc

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml

Précision sur : 
- le format de la date
- le caractère déclaratif de la donnée

Ajout de la date dans les données transmises

---

.rubocop.yml

Ref https://stackoverflow.com/a/75724258

Rubocop: speed up

---

Makefile

Je merge au vert pour @DorineLam

Fix docker-compose file for new syntax

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Ajoute l'API Actes et bilans dans les cas d'usages, dont marchés publics :

Cas d'usages des actes et bilans

---

app/controllers/admin/editors_controller.rb
app/views/admin/editors/edit.html.erb
app/views/admin/editors/index.html.erb
config/routes.rb
spec/features/admin/editors_spec.rb

https://www.loom.com/share/eeae355df4914f52a307054515da6049

Admin: can update editors

---

app/views/api_entreprise/pages/newsletter/_main.html.erb
app/views/api_particulier/pages/newsletter/_main.html.erb

Sometimes not loading the height correctly, we need to set a hard value

fix: bug newsletter iframe

---

app/controllers/api_entreprise/download_attestations_controller.rb
spec/features/api_entreprise/download_attestations_spec.rb

admin user can't access attestations page through pretender

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Termine les cas d'usages liens capitalistiques

---

db/schema.rb

Répétition de #1758 qui a été réécrasée sans doute par inadvertence.

Re-re-correction de schema.rb pour access logs

---

app/controllers/api_particulier/reporters_controller.rb
app/facade/token_stats_facade.rb

Maybe the recent metabase migration ?

BUGFIX Invalid Metabase resource

---

config/locales/api_entreprise/fr.yml

Juste pour régler le soucis spécifique du client, mais on va changer le système entièrement bientôt

add beneficiaires effectifs to locales

---

config/endpoints/api_particulier/cnaf_msa_quotient_familial_v2.yml

Fix erreur yml de la dernière PR mergée

---

db/migrate/20250326104012_migrate_tokens_scopes_to_api_particulier_v3.rb
db/schema.rb

It's only added scopes, no remove, so it's kind of safe here. Tested locally.
Ref https://github.com/etalab/data_pass/pull/740

Migrate scopes to API Particulier v3

---

config/endpoints/api_entreprise/9_douanes_eori.yml

Ajouter la doc d'acutalisation de la donnée pour l'API EORI :

[API Entreprise] Documentation actualisation Numéro EORI

---

app/views/shared/authorization_requests/index.html.erb

rename button in list of authorizations

---

app/views/editor/authorization_requests/index.html.erb
app/views/shared/tokens/_detail_short.html.erb

Bug introduced by 68ec37ffdef333be638db4305e81b0328cfb8621

Editor: Do not display extra reveal button

---

app/controllers/concerns/prolong_token_wizard_management.rb
app/helpers/external_url_helper.rb
spec/helpers_spec/external_url_helper_spec.rb

Old redirection no longer works

Change DataPass reopen link to match v2

---

config/endpoints/api_particulier/cnav_complementaire_sante_solidaire.yml

Les informations sur la participation financière ne sont pas fiables sur cette API. Une correction est prévue par la CNAV en novembre 2025.
Nous mettons une alerte en attendant

Alert api css

---

config/endpoints/api_entreprise/dgfip_liens_capitalistiques.yml

https://linear.app/pole-api/issue/API-5138/retirer-le-tag-beta-de-lapi-liens-capitalistiques

Closes https://linear.app/pole-api/issue/API-5138/retirer-le-tag-beta-de-lapi-liens-capitalistiques

---

config/locales/api_entreprise/cas_usages_entries.fr.yml

Vu rapide, il y a aussi le contenu pour chaque cas d'usage : <img width="1102" height="571" alt="image" src="https://github.com/user-attachments/assets/1a237a42-cc51-4ca6-8276-24ffd623e319" />

[API-4066] Initie les cas d'usages pour l'API data subvention

---

app/views/shared/pages/accessibility.html.erb

Mis à jour du Schema pluriannuel du Pôle Ouverture et circulation de la donnée.
